### ISSUE TITLE
Ability to get Cucumber.js output instead of Nightwatch.js

### ISSUE THREAD

**Issue by mucsi96** [mucsi96/nightwatch-cucumber#10]

**Comment by mucsi96** [comment]
The output format depends on which framework is actually running the tests. Nightwatch or Cucumber. Both contains a command line runner feature.

The latest commit with Cucumber output was https://github.com/mucsi96/nightwatch-cucumber/tree/8cf10ae2ffdc9ae3f9bbf140a8696daa119893a4. Where Nightwatch was used like an API. 
The problem with this approach was that you manually need to take care of nightwatch `.end` function call it the last step of scenario. This function is used start the execution and then close the selenium session and browser. Also you need to manually start selenium server.

Other solution could be to run using nightwatch runner but get an output similar to cucumber. But I have no idea how to make it. :) The best would be if both frameworks expose all functionality as an API.

**Comment by RSsimranjeetsingh** [comment]
Is there any update on this?

**Comment by mucsi96** [comment]
No. This needs a total rewrite :(

**Comment by mucsi96** [comment]
The easier solution is to run using nightwatch runner but get an output similar to cucumber. But I have no idea how to make it. :)

**Comment by Garethp** [comment]
A better solution which I came across is to try and decouple the NightwatchJS client from the NightwatchJS Test Runner, and pass it in to Cucumber directly. I made an example here https://github.com/Garethp/cucumber-nightwatch

**Comment by mucsi96** [comment]
Thanks for the solution. Its the opposite solution to the Nightwatch-Cucumber problem :)

**Comment by mucsi96** [comment]
Initially I started with a very similar solution.

**Comment by Garethp** [comment]
Maybe some documentation in the main nightwatch project could be added to make it clearer how to separate the API client from the Test Runner itself. Being able to do that would give Nightwtch more flexibility in how and where it can be run

**Comment by mucsi96** [comment]
+1 I also think that Cucumber.js should also separate the API client from the Test Runner itself.
