### ISSUE TITLE
Parallel run with remote selenium

### ISSUE THREAD

**Issue by klokovas** [mucsi96/nightwatch-cucumber#108]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
If I run the tests in parallel using a remote server, I get this error: 
There was an error while starting the test runner:

`"Error: No source folder defined. Check configuration."`

In normal start - everything is OK. 
The problem is repeated if the server is run locally but separately.

When using `selenium-server` module (both in test examples), there is no problem.

**Please tell us about your environment:**
Configuration:
```
require('babel-core/register');
require("babel-polyfill");

require('nightwatch-cucumber')({
    stepDefinitions: ['step_definitions'],
    supportFiles:    ['hooks/hooks.js']
});

module.exports = {
  output_folder           : 'reports',
  custom_commands_path    : '...',
  custom_assertions_path  : '....',
  page_objects_path       : '....',
  globals_path            : '...',

  test_workers: true,

  test_settings : {
    default: {
      ...
    },

    remote : {
      launch_url     : 'example.com',
      selenium_host  : 'selenium-host',
      selenium_port  : 4444
    }
  }
};
```

* **nightwatch-cucumber version:**
`"nightwatch-cucumber": "5.1.0",`
* **nightwatch version:**
`"nightwatch": "^0.9.8",`
* **cucumber version:**
`"cucumber": "1.3.1",`
* **Node.js version:**
`6.3.1`

*P.S.*

Please Sorry for bad english.

**Comment by mucsi96** [comment]
Hi @klokovas! Thanks for the feedback! I will check this.
