### ISSUE TITLE
Error when used with gulp-cucumber

### ISSUE THREAD

**Issue by arnogues** [mucsi96/nightwatch-cucumber#109]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
When I use gulp-cucumber, I got an error 
```
TypeError: Cannot read property 'length' of undefined
    at Object.ClientRunner.getTestSource (/<project>/client/node_modules/nightwatch-cucumber/lib/nightwatch-api.js:77:28)
    at Object.runner (/Users/arnogues/Documents/dev/nop/client/node_modules/nightwatch/lib/runner/cli/clirunner.js:422:21)
    at /<project>/client/node_modules/nightwatch/lib/runner/cli/clirunner.js:395:12
    at /<project>/client/node_modules/nightwatch/lib/runner/cli/clirunner.js:338:9
    at beforeGlobal (/<project>/client/node_modules/nightwatch/lib/runner/cli/clirunner.js:334:89)
    at Object.startSelenium (/<project>/client/node_modules/nightwatch/lib/runner/cli/clirunner.js:337:20)
    at Object.runTests (/<project>/client/node_modules/nightwatch/lib/runner/cli/clirunner.js:394:10)
    at Object.exports.runner (/<project>/client/node_modules/nightwatch/lib/index.js:543:39)
    at /<project>/client/node_modules/gulp-nightwatch/lib/background.js:17:14
    at Object.exports.cli (/<project>/client/node_modules/nightwatch/lib/index.js:537:5)
```

**Expected/desired behavior**
Nightwatch should be launched like if I start it from the CLI.

**Reproduction of the problem**
Just use gulp-cucumber.

**Please tell us about your environment:**
OSX El Capitan

* **nightwatch-cucumber version:** 5.1.0
* **nightwatch version:** 0.9.8

* **cucumber version:** 1.3.1

* **Node.js version:** 6.5.0

I know where is the problem, in the 
`nightwatch-cucumber/lib/nightwatch-api.js` file
At line 77 you have this code : 
```javascript
     if (this.argv._source.length) {
        this.argv._source[0] = convert(this.argv._source[0])
      } else if (this.argv.test) {
        this.argv.test = convert(this.argv.test)
      } else {
        this.settings.src_folders = self.modulePaths
      }
```

It tries to directly test `this.argv._source.length`, but this.argv._source.length doesn't exists when we start from `gulp-cucumber``
Then the fix is : 
```javascript
      if (this.argv._source && this.argv._source.length) {
        this.argv._source[0] = convert(this.argv._source[0])
      } else if (this.argv.test) {
        this.argv.test = convert(this.argv.test)
      } else {
        this.settings.src_folders = self.modulePaths
      }
```

I tested it and it fixed the problem

**Comment by mucsi96** [comment]
Hi @arnogues! Thanks for the feedback! I will check this.

**Comment by mucsi96** [comment]
Thanks for the fix! Can you provide more details about using `gulp-cucumber` with `nightwatch-cucumber`. May be I can provide it in the readme. It could be useful for others as well. Thanks 👍

**Comment by arnogues** [comment]
My apologizes but the error was not with `gulp-cucumber` but with `gulp-nightwatch`, I think I was a little tired :(
