### ISSUE TITLE
Provide Nightwatch api as a require able module.

### ISSUE THREAD

**Issue by mucsi96** [mucsi96/nightwatch-cucumber#110]

**Comment by jeremyrajan** [comment]
https://github.com/mucsi96/nightwatch-cucumber/issues/121 ? :)

**Comment by mucsi96** [comment]
This is different from you need. This is about providing Nightwatch API as require able module instead of passing it as context to step definitions.

```
const browser = require('nightwatch-cucumber').nightwatchClient;

module.export = function() {
  this.Given('test step', function () {
    browser.init();
    browser.click('.my-button');
  });
}
```
That would add support for arrow functions :)
```
const browser = require('nightwatch-cucumber').nightwatchClient;

module.export = function() {
  this.Given('test step', () => {
    browser.init();
    browser.click('.my-button');
  });
}
```

**Comment by jeremyrajan** [comment]
Ahh alright :). My bad.

**Comment by mucsi96** [comment]
This is no longer needed as from now (release `5.6.0`) Nightwatch client could be provided as first parameter for the step definition functions.
