### ISSUE TITLE
Specify gerkin language

### ISSUE THREAD

**Issue by arnogues** [mucsi96/nightwatch-cucumber#118]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
Gerkin language is in english (When, Then, Given)

**Expected/desired behavior**
Gerkin language in other language like french "Et que", "Mais que"

I don't see any parameters to set it

**Comment by mucsi96** [comment]
Thanks for feedback! Is it possible in Cucumber.js?

**Comment by mucsi96** [comment]
@arnogues I added a section about language to readme https://github.com/mucsi96/nightwatch-cucumber#language
