### ISSUE TITLE
Examples of how to use the hooks/event handlers

### ISSUE THREAD

**Issue by JonWallsten** [mucsi96/nightwatch-cucumber#119]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
There are no examples for hooks/event handlers in the examples folder. Event handlers seems to be pretty straight forward how to use. But not hooks.

**Expected/desired behavior**
I would like to see examples of how to use hooks and event handlers in the project's examples folder.
Preferably with a use example of this nightwatch API.

**Comment by jeremyrajan** [comment]
Upvote for this. I am trying to use hooks like so, below:

### hooks.js
```
module.exports = function () {
  this.registerHandler('BeforeStep', function (step, callback) {
    console.log('before step')
    callback();
  });
}
```

my nightwatch config is:

```
const featureFiles = [process.env.FEATURE_FILES];
const stepDefinitions = [path.join(__dirname, 'step-definitions')];
const customCommands = path.join(__dirname, 'commands');
const globals = path.join(__dirname, 'globals.js');
const hooks = path.join(__dirname, 'hooks.js');

require('nightwatch-cucumber')({
  featureFiles: featureFiles,
  stepDefinitions: stepDefinitions,
  stepTimeout: 10000,
  supportFiles: [hooks]
});

module.exports = {
...
}
```

Apparently, only `AfterFeatures` hook seems to work and nothing else. When using `BeforeStep` the browser opens up and hangs till it times out.

![image](https://cloud.githubusercontent.com/assets/2890683/19302595/52294eda-9097-11e6-8f99-ccbc36bd4622.png)

If I don't use the hooks at all, everything works perfectly fine.

Not sure, is it the way i am including it. Any help will be highly appreciated.

Thank you!
