### ISSUE TITLE
Keep browser instance open

### ISSUE THREAD

**Issue by louiscbotha** [mucsi96/nightwatch-cucumber#12]
Currently, new browser instances are opened and closed per feature. How do I force the browser session to stay open and for the features to reuse the same browser session?

Usually, one could add the background section to setup the scenario (login etc.) but your implementation doesn't seem to support background data.

**Comment by mucsi96** [comment]
I think this is a limitation of Selenium itself. Reusing Selenium session is considered a bad practice :( Because of session failure case.

**Comment by louiscbotha** [comment]
Keeping the browser session open between features works perfectly with Nightwatch and Yadda. Take a look at https://github.com/kjelloe/Yadda-NightwatchJS

**Comment by mucsi96** [comment]
That's great news! thanks. I will try to fix this

**Comment by mucsi96** [comment]
I checked the Yadda-NightwatchJS integration. I think it is not perfect because it is mapping all feature files into a single nightwatch test. This will give strange output from Nightwatch This implementation is mapping multiple feature files to multiple Nightwatch tests. That's why keeping browser instance open depends on a Nightwatch issue https://github.com/nightwatchjs/nightwatch/issues/117

**Comment by louiscbotha** [comment]
Wouldn't it be better to allow for this via a config setting? This could temporarily solve the issue for some people but won't necessarily be the most ideal fix.

**Comment by volodya1805** [comment]
hey Igor. Any luck with that issue?

**Comment by mucsi96** [comment]
Not yet :( But for speed up I suggest to try paralell test execution. 
```
"test_workers": true 
```
More details [here](http://nightwatchjs.org/guide#parallel-running)

**Comment by volodya1805** [comment]
Yeah i know about paralell test execution, but that's the only one blocker why we don't use this module.

**Comment by volodya1805** [comment]
Igor, can you please give me an update on that. If you are not going to fix that in the near feature we are going to search any other solution instead of using your nightwatch + cucmber integration.

**Comment by mucsi96** [comment]
I started to work on this. I can see two possible solutions for this:
- Fix https://github.com/nightwatchjs/nightwatch/issues/117
- Add a `runner` option with default value `nightwatch`. If the user set it to `cucumber` than cucumber will be the main runner. In this case Nightwatch runner features will be not available. (Like parallel execution) Also the output will be Cucumber style.

For cucumber runner mode we can create an additional option to use single browser session like in  https://github.com/kjelloe/Yadda-NightwatchJS

What do you think?

**Comment by volodya1805** [comment]
I think it's ok since we can use browser stack for parallel execution - right?

**Comment by mucsi96** [comment]
Ok. I plan to fix it this week.

**Comment by volodya1805** [comment]
if it quick fix - please add a check for now:  if we execute the latest scenario from the current feature in this case close browser session otherwise keep browser instance open

**Comment by volodya1805** [comment]
because right now instances are opened and closed per every screnario in the feature

**Comment by mucsi96** [comment]
Yes because `.end()` is added after every scenario in the feature. This causes the problem https://github.com/nightwatchjs/nightwatch/issues/117#issuecomment-39190581

**Comment by anatoliyarkhipov** [comment]
Sorry if it's not a correct place for the question, but I think it's somehow related. Is there a way to keep nightwatch always run? Something like "live" or "interactive" mode, where Nightwatch can re-run the tests without rerunning everything else (Selenium, browser).

**Comment by mucsi96** [comment]
Hi! I am not sure I understand you correctly. Do you think about a REPL like executing `node` from terminal? Where you entera nightwatch command, hit Enter and it will be executed inbrowser using selenium?

**Comment by anatoliyarkhipov** [comment]
No, sorry. Let me try to explain. In this thread you made it possible to not close the browser after every scenario. It's very cool, it speeds up the tests.

And I want to go further, something like "watch" mode from unit tests frameworks, when they don't stop the process after running all tests but waits for files changes. In case of Nightwatch it means that it doesn't run Selenium and browser every time when I need to run the tests but keeps them opened.

Does it make sense?

**Comment by anatoliyarkhipov** [comment]
The main problem for me is slow start. When I'm working on a single test it prevents me from running it often. The test itself takes ~3 seconds but starting of it takes ~12 seconds. The most part of this time is the browser opening. It's why I'm asking about something like "watch" mode.

I tried to start Selenium in a parallel process, but it doesn't help, because Nightwatch is still opening the browser on every run. 

It looks like I'm missing something obvious.

**Comment by anatoliyarkhipov** [comment]
Okay, I created an express proxy between Nightwatch and Selenium, and I cache the first created session while the proxy is running. So I can reuse the same browser window between test runs. It's still taking some time for running the Nightwatch itself, but the current situation is much better. My problem has gone, sorry for bothering 😅

**Comment by mucsi96** [comment]
Wow! Nice. I think creating a watch mode is a very good idea. But I feel that it should be part of the Nightwatch package. Not this one. I am closing this for now

**Comment by anatoliyarkhipov** [comment]
Actually, after the proxy, I implemented a "watch mode". Now it takes 0 seconds to re-run the tests. But my implementation uses some hacks and relies on the fact, that `Runner#run` is overloaded by `nightwatch-cucumber`. So I'm not sure where should I continue this discussion and should I continue it at all. If someone interested, I can split the "watch mode" code from our application code and puslish a repo.

**Comment by mucsi96** [comment]
I think this shoul be part of Nightwatch. But they are not very active now. I have an open pull request for month

**Comment by mucsi96** [comment]
This is the bad barts of open source

**Comment by tegomass** [comment]
+1

**Comment by cengiz-a** [comment]
I´m fascinated by the idea of a watch mode in nightwatch like nodejss nodemon. That method would save so much time!  Could you show /share your solution with that express proxy? Thanks.

**Comment by anatoliyarkhipov** [comment]
Unfortunately, I switched my job and don't have access to the code. As I remember the "watch mode" consisted of two parts:
1. The `express` proxy. It was pretty simple - it redirected every request to the real Selenium, but if it was a request to create a browser instance, than the proxy checked if it had been already created and returned its session ID if it had
1. Another part was to override `Runner#run` and that was full of dirty hacks which I wouldn't be able to remember now

Actually, for now I use Cypress and it works just fine.
