### ISSUE TITLE
Parallel mode and tags incompatibility

### ISSUE THREAD

**Issue by aberonni** [mucsi96/nightwatch-cucumber#120]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
The runner crashes when trying to use tags/groups in parallel mode. 
This can be encountered when you specify tags in the command line and:
- use multiple environments =>
`nightwatch --env default,chrome --tag google`
- or `test_workers` is enabled in nightwatch.conf.js

**Expected/desired behavior**
The runner should not crash

**Reproduction of the problem**
I tried creating a [c9 workspace](https://ide.c9.io/aberonni/test), it is the first time i use it so please let me know if you cannot access it. 
Just running `npm test` in that workspace will launch `nightwatch --env default,chrome --tag google` and reproduce the error.

**Comment by mucsi96** [comment]
Hi @aberonni! Thanks for your feedback! I can access the c9 workspace. And really appreciate it 👍

**Comment by aberonni** [comment]
Always super quick!! Thank you! 😄

**Comment by jagadeeshshetty** [comment]
Is it fixed?
