### ISSUE TITLE
 If the step fails it is waiting cucumber timeout instead put error message immediately.

### ISSUE THREAD

**Issue by klokovas** [mucsi96/nightwatch-cucumber#127]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
 If the step fails it is waiting cucumber timeout instead put error message immediately.

**Reproduction of the problem**

1) I take `/examples/background-example`
2) Change url from `google.com` to `google2.com`
3) Step fails and is waiting cucumber timeout instead put error message immediately.

```
  Scenario: Addition
  ✔ Given I open Google's search page
  ✖ When I search for 500+120
  - Then the search result should contain 621

  Scenario: Division
  ✖ Given I open Google's search page
  - When I search for 36/6
  - Then the search result should contain 6

Failures:

1) Scenario: Addition - features/google.feature:6
   Step: When I search for 500+120 - features/google.feature:8
   Step Definition: features/step_definitions/steps.js:8
   Message:
     function timed out after 30000 milliseconds
```

**Please tell us about your environment:**

* **nightwatch-cucumber version:**
     `"nightwatch-cucumber": "5.5.2",`

* **nightwatch version:**
    `"nightwatch": "^0.9.8"`    

* **cucumber version:**
    `"cucumber": "1.3.1",`

* **Node.js version:**
`6.3.1`

**Comment by mucsi96** [comment]
Hi @klokovas! Thank you for the feedback! I will check it

**Comment by mucsi96** [comment]
I could not reprodice it. My error is: 
```
ERROR: Unable to locate element: "input[name=q]" using: css selector                                             
    at Object.<anonymous> (C:\Users\mucsi\repos\nightwatch-cucumber\examples\background-example\features\step_def
initions\steps.js:10:8)                                                                                          
    at F.nightwatch.perform.err (c:\Users\mucsi\repos\nightwatch-cucumber\lib\nightwatch-api.js:135:16)
```

I have the same versions

**Comment by klokovas** [comment]
Yes. The error is not always reproduced (sporadic bug)). Also I run on the chrome, not on phatom.

**Comment by klokovas** [comment]
This my result
![2016-10-20_23-07-12](https://cloud.githubusercontent.com/assets/8973021/19576022/1dd40970-971a-11e6-95d3-0ad177473e55.png)

**Comment by klokovas** [comment]
My config:

```
var seleniumServer = require('selenium-server')
//var phantomjs = require('phantomjs-prebuilt')
var chromedriver = require('chromedriver')

require('nightwatch-cucumber')()

module.exports = {
  output_folder: 'reports',
  custom_commands_path: '',
  custom_assertions_path: '',
  live_output: false,
  disable_colors: false,

  selenium: {
    start_process: true,
    server_path: seleniumServer.path,
    log_path: '',
    host: '127.0.0.1',
    port: 4444
  },

  test_settings: {
    default: {
      launch_url: 'http://localhost',
      selenium_port: 4444,
      selenium_host: 'localhost',
      silent: true,
      screenshots: {
        enabled: true,
        on_failure: true,
        on_error: false,
        path: 'screenshots/default'
      },
desiredCapabilities: {
        browserName: 'chrome',
        javascriptEnabled: true,
        acceptSslCerts: true
      },
      selenium: {
        cli_args: {
          'webdriver.chrome.driver': chromedriver.path //I changed from phantom to chrome
        }
      }
    },

    chrome: {
      desiredCapabilities: {
        browserName: 'chrome',
        javascriptEnabled: true,
        acceptSslCerts: true
      },
      selenium: {
        cli_args: {
          'webdriver.chrome.driver': chromedriver.path
        }
      }
    },

    firefox: {
      desiredCapabilities: {
        browserName: 'firefox',
        javascriptEnabled: true,
        acceptSslCerts: true
      }
    }
  }
}
```

**Comment by klokovas** [comment]
And in report I see:
![2016-10-20_23-17-31](https://cloud.githubusercontent.com/assets/8973021/19576377/706c6262-971b-11e6-88c9-e1c360836b38.png)

**Comment by klokovas** [comment]
On *phantomjs* I have the same problem.
But there is a problem with the report, which was previously fixed (https://github.com/mucsi96/nightwatch-cucumber/pull/91). The error text does not contains stacktrace - see the screenshot above.

**Comment by klokovas** [comment]
@mucsi96 , Could you try using chrome instead of phantomjs?
I can not understand what I'm doing is wrong)

If the error is not reproduced on this time, then of course I'll close the issue.

**Comment by mucsi96** [comment]
@klokovas I have the same in chrome. Sorry :(

**Comment by mucsi96** [comment]
Can you try the same without `nightwatch-cucumber` plugin. Using plain nightwatch? Is the problem stil exists?

**Comment by klokovas** [comment]
Ok, thanks. I close issue.
