### ISSUE TITLE
Pulling more than one feature file.

### ISSUE THREAD

**Issue by Ceyaje** [mucsi96/nightwatch-cucumber#13]
Perhaps we're doing something wrong, but this project doesn't run out of the box, and we needed to edit globals/cucumber.js at lines 42 (lookupStepDefinitionsByName --> lookupStepDefinitionByName) and 57 (removing [0], as stepDefinitions is not an array). After making those changes, finally everything runs, however only one feature--the first alphabetically--is run.

How can this be fixed to be able to run MULTIPLE features.

**Comment by mucsi96** [comment]
Thanks for feedback. I will check this today

**Comment by louiscbotha** [comment]
Not sure if it's related to the previous fix https://github.com/mucsi96/nightwatch-cucumber/issues/6 but maybe check it out.

**Comment by Ceyaje** [comment]
I noticed #6 after I posted this, but it doesn't seem to be related. The code seems to have changed greatly since then.

**Comment by mucsi96** [comment]
I bumped Cucumber version to the latest one `0.9.2`. Now it seems ok

**Comment by Ceyaje** [comment]
Thanks man!
