### ISSUE TITLE
report problem

### ISSUE THREAD

**Issue by Alfredo81** [mucsi96/nightwatch-cucumber#133]
**I'm submitting a ...**  (check one with "x")

```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
if i have 5 different .feature files in 1 group folder and use the --group option ,the tests run in parallel mode but at the end only the last is captured by the report.

**Expected/desired behavior**
a report for each .feature test

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://c9.io, http://www.koding.com, https://www.nitrous.io or similar.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

+-- cucumber@1.3.1
+-- nightwatch@0.9.8
+-- nightwatch-cucumber@4.2.0
- **Node.js version:**
  6.1.0

**Comment by mucsi96** [comment]
Hi @Alfredo81! I could not reproduce the issue with the latest version (`5.6.0`) Can you try to update and provide a feedback?

**Comment by Alfredo81** [comment]
sure dude i'll try and give you a feedback asap!

**Comment by Alfredo81** [comment]
with the latest version(the 5.6.0) work perfectly...i close the issue.thank you so much
