### ISSUE TITLE
 run tagged scenarios when test_workers set true

### ISSUE THREAD

**Issue by shacall** [mucsi96/nightwatch-cucumber#137]
**Current behavior**
I've tried out to run the tests in parallel mode with test_workers and everything works fine, untill I tried out to start the tests with the --tag command. Then I've got the following error:

```
Starting selenium server in parallel mode... started - PID:  1741

Error: No tests defined! using source folder: /var/folders/k2/nwj5msy55kbbwd0w1p7l0_p40000gp/T/tmp-1740JgYOOuUi6NaB/tests/nightwatch-cucumber/features ; using tags: startPage
    at /Users/xxx/Projekte/karriere_at_k4/node_modules/nightwatch/lib/runner/run.js:205:20
    at /Users/xxx/Projekte/karriere_at_k4/node_modules/nightwatch/lib/runner/walk.js:161:15
    at /Users/xxx/Projekte/karriere_at_k4/node_modules/nightwatch/lib/runner/walk.js:67:17
    at /Users/xxx/Projekte/karriere_at_k4/node_modules/nightwatch/lib/runner/walk.js:76:13
    at FSReqWrap.oncomplete (fs.js:123:15)

```

**Please tell us about your environment:**

* **nightwatch-cucumber version:** v5.6.0

* **nightwatch version:** v0.9.8

* **cucumber version:** v1.3.1

* **Node.js version:** v6.4.0

**Comment by mucsi96** [comment]
Hi @shacall! Thanks for the feedback! I will look at it

**Comment by Frikki** [comment]
Perhaps @madroneropaulo’s fix that is referenced can shed some light on the issue and a fix.

**Comment by mucsi96** [comment]
Thanks @Frikki and @madroneropaulo! Your fix was used with an e2e test added.
