### ISSUE TITLE
document supported nightwatch command line options

### ISSUE THREAD

**Issue by mucsi96** [mucsi96/nightwatch-cucumber#139]

**Comment by AlfredoMoretta** [comment]
@mucsi96  i'm not sure if i understand but you can link this page for satisfactory documentation for command line options https://github.com/nightwatchjs/nightwatch-docs/blob/master/guide/running-tests/

**Comment by mucsi96** [comment]
Thanks @AlfredoMoretta !

**Comment by AlfredoMoretta** [comment]
you're welcome mate!
