### ISSUE TITLE
Not able to execute multiple Scenarios in a feature file

### ISSUE THREAD

**Issue by RSsimranjeetsingh** [mucsi96/nightwatch-cucumber#14]
Hi,

I am not able to execute multiple scenarios in a feature file.
When i try to do so, it always gives this generic error message which is difficult to debug:

<quote>
ERROR There was an error while starting the test runner:
Error: External global file could not be located - using globals/cucumber.js.
</quote>

PS : Also, I have noticed that whenever there is any typo error in the feature file, then the above error is always shown. This way it becomes very difficult to debug the cause of the error.
Can you please suggest any workaround, how to debug such issues.

Awaiting response.....

Thanks

**Comment by mucsi96** [comment]
Thanks for feedback. I will try to check this. Debugging in Node.js was always a pain :(

**Comment by RSsimranjeetsingh** [comment]
No Worries Igor :)
I found the solution in the Alex's forked project in the recent commit.
https://github.com/AlexMurphy/nightwatch-cucumber/commit/77cda1013030e8743b2e9b84d65c6339e6c8e43c

Request you to kindly merge the changes here as well, so that visiting users should not face this issue.

Many Thanks
Simran

**Comment by RSsimranjeetsingh** [comment]
Closed with this pull request:
https://github.com/mucsi96/nightwatch-cucumber/pull/15

**Comment by mucsi96** [comment]
Thanks for the fix!
