### ISSUE TITLE
report with date/time 

### ISSUE THREAD

**Issue by AlfredoMoretta** [mucsi96/nightwatch-cucumber#145]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
report produce only the html for the last test run

**Expected/desired behavior**

will be very helpfull if report will produce html like this:

cucumberhtml[date/time].html and don'rewrite always itself

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://c9.io, http://www.koding.com, https://www.nitrous.io or similar.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **nightwatch-cucumber version:**

* **nightwatch version:**

* **cucumber version:**

* **Node.js version:**

**Comment by mucsi96** [comment]
Hi @Alfredo81! Thanks for the feedback! Thats a great idea. What do you think if we allow providing a function for `htmlReport` and `jsonReport` configuration options? Can you help with providing a pull-request for that?

**Comment by AlfredoMoretta** [comment]
@mucsi96 i've done something like that for my project i hope it can help for you and other guys:

const mkdirpSync = require('mkdirp').sync,
      fs = require('fs-extra')

const helperDateTime = {

    logging:  () => {

        let today = new Date();

        var sToday = today.getFullYear().toString()
        sToday += ("0" + today.getMonth() + 1).slice(-2)
        sToday += ("0" + today.getDate()).slice(-2)

        var sRightTime = ("0" + today.getHours()).slice(-2)
        sRightTime += ("0" + today.getMinutes()).slice(-2)
        sRightTime += ("0" + today.getSeconds()).slice(-2)


        try  {
            mkdirpSync('reports-' + sToday)
            fs.copySync('reports/cucumber.html', 'reports-' + sToday + '/cucumber-' + sRightTime + '.html')
            fs.copySync('reports/cucumber.html', 'reports/NightwatchResult.html')
        } catch (err) {
            console.log (err)
        }

        return this;

    }
}

module.exports = {
    commands: helperDateTime,
    elements: {}
}

**Comment by AlfredoMoretta** [comment]
@mucsi96  did you like this solution?

**Comment by mucsi96** [comment]
Hi @AlfredoMoretta ! Thanks for sharing it! I looks good. I cannot integrate this into the project currently as cucumber html reporting was delegated to https://github.com/gkushang/cucumber-html-reporter package.
