### ISSUE TITLE
Single step timeout is ignored

### ISSUE THREAD

**Issue by aberonni** [mucsi96/nightwatch-cucumber#159]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Single step timeout is ignored in favor of global `stepTimeout` option

**Expected/desired behavior**
Single step timeout should be taken into consideration

**Reproduction of the problem**

You can reproduce the bug by running `npm test` in this [c9 workspace](https://ide.c9.io/aberonni/test).

I am trying to set single step timeout as explained [here](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/timeouts.md).

```js
  this.Given(/^a slow step$/, {timeout: 60 * 1000}, function() {
    // Does some slow browser/filesystem/network actions
  });
```

Unfortunately it seems that the global option `stepTimeout` is always taken into consideration instead of the timeout set on the single step, 

I tried looking into the code that handles this behavior but I can't figure out where the issue is.

* **nightwatch-cucumber version:**
5.6.6
* **nightwatch version:**
0.9.9
* **cucumber version:**
1.3.1
* **Node.js version:**
6.3.1

**Comment by mucsi96** [comment]
Hi @aberonni! Thanks for feedback!

**Comment by mucsi96** [comment]
Hi @aberonni! Now everything should work with the latest version. Please check the docs as a lot of things has changed. Also from now the Cucumber.js default timeout is used. Which is rather small for Selenium testing :)
