### ISSUE TITLE
Screenshot is causing error when step fails (OS X only)

### ISSUE THREAD

**Issue by JonWallsten** [mucsi96/nightwatch-cucumber#161]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
Screenshot is not taken when step fails and the following error is generated
```
RangeError: Maximum call stack size exceeded
    at CucumberAPI.handleAttachments (/myPath/lib/cucumber-api.js:61:42)
    at next (native)
    at PrettyFormatter.<anonymous> (/myPath/node_modules/nightwatch-cucumber/lib/cucumber-api.js:87:24)
    at next (native)
    at onFulfilled (/myPath/node_modules/nightwatch-cucumber/node_modules/co/index.js:65:19)
```

**Expected/desired behavior**
Screenshot should be taken. No error should occur.

**Reproduction of the problem**
Install latest Cucumber RC and Nightwatch Cucumber 6.x.x.
Run a test with a step that will fail.

**What is the expected behavior?**
Should save screenshot and not generate error

**What is the motivation / use case for changing the behavior?**
It was previously working and is needed.

**Please tell us about your environment:**
OSX 10.11.6
* **nightwatch-cucumber version:**
6.1.1
* **nightwatch version:**
0.9.9
* **cucumber version:**
2.0.0-rc.2
* **Node.js version:**
6.6.0

**Comment by mucsi96** [comment]
Hi @JonWallsten! Thanks for the feedback! Can you help with fixing that? I am rather busy nowadays.

**Comment by JonWallsten** [comment]
Looking into it now,

**Comment by JonWallsten** [comment]
It was not OS X specific but happened on Macbook Pro due to it's pixel density.
A bigger buffer caused "RangeError: Maximum call stack size exceeded" when the array was applied instead of looped. 

See following PR: https://github.com/mucsi96/nightwatch-cucumber/pull/166
