### ISSUE TITLE
Code organization

### ISSUE THREAD

**Issue by madroneropaulo** [mucsi96/nightwatch-cucumber#162]
**I'm submitting a ...** 
```
[x ] feature request
```
*Improve code organization.*

**What is the motivation / use case for changing the behavior?**
To promote contributing and building a more stable package version.
Prevent contributors from wasting time trying to understand what others already figured out.
Improve code maintainability

**Proposal:**
1 -  Use jsDocs. http://usejsdoc.org/ If you know the shape of the arguments a function is expecting, write it with jsdocs syntax. That is a very big time-saver feature.
2 - Methods / functions should not be longer than 10-15 lines. This is a key best practice when the code is supposed to be maintained by several people. https://refactoring.guru/smells/long-method http://softwareengineering.stackexchange.com/a/133406/256102
3 - Scheme the workflow. It is useful to understand the big picture of the workflow, only trying to understand it takes too much time, if someone already understands it, drawing some diagram will help everyone (and himself, when he gets back to the code). https://www.draw.io/ - nice free tool for drawing diagrams.

I believe these points should be implemented (at least partially) before writing any new code, and all the new code should implement points 1 and 2. Otherwise the entropy will only grow, and at some point the package will become unmaintainable.

**Comment by mucsi96** [comment]
Hi @madroneropaulo! Wow that's are very good ideas! Can you help with that? I am rather busy nowadays

**Comment by mucsi96** [comment]
Hi @madroneropaulo! with the new release 7.0.0 the code has been simplified. I would like to simplify it much more in the future. Currently there is a lot of Nightwatch patching in the code. My plan is to use Nightwatch throght an API only as a client. And the whole test execution should be handled by Cucumber.js. The only blocker is that Nightwatch supports profiles and execution. It is currently not the case with Cucumber.js. The best would be if this package will be not needed :)
