### ISSUE TITLE
Implement Eslint

### ISSUE THREAD

**Issue by JonWallsten** [mucsi96/nightwatch-cucumber#165]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```
I would like to implement linting rules for the project to keep the code consistent now when you need more help from the outside. Would this be ok? Do you have any preferences?

**Comment by mucsi96** [comment]
I have eslint in the project. I use standard based ruleset.

**Comment by JonWallsten** [comment]
Ah, okey, I guess we have a more strict ruleset in our product.
In my opinion the code could be much more easier to read with some changes in the linting.
But it's up to you. I'm up for the job.

**Comment by mucsi96** [comment]
Thanks! That's amazing! Can your propose a ruleset? I am open for any change.

**Comment by JonWallsten** [comment]
I'll do that. Can also provide a before/after. It is pretty strict, but in my experience it's the only way to keep the code clean. And you adapt really quick even though it's annoying in the beginning. I'll let you decide later.

**Comment by JonWallsten** [comment]
https://github.com/JonWallsten/nightwatch-cucumber/commit/fa4c1771a108ca2210c497011b481788cd1324c8?diff=split

**Comment by Frikki** [comment]
@JonWallsten 

> in my experience it's the only way to keep the code clean

How has this got anything to do with clean code? For reference, https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882

**Comment by JonWallsten** [comment]
Clean = structrued

**Comment by Frikki** [comment]
Sure, a linter can help developers maintain a consistent code style.

**Comment by mucsi96** [comment]
I would not like to include a custom made eslint config if possible. I would like to include a complete eslint preset. I have used the eslint-config-standard. But I am open to switch to eslint-config-airbnb-base or anything else. I think its more battle tested than creating one from stretch. What do you think?
