### ISSUE TITLE
Issue with cucumber 2.0.0-rc.4

### ISSUE THREAD

**Issue by damitas** [mucsi96/nightwatch-cucumber#168]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
step definitions are not being recognised from my step definition.js in /step_definitions.  They are being displayed as undefined and pending

**Expected/desired behavior**
Steps are found as they exist in my step definitions.

**Please note there are no issues with cucumber version 2.0.0-rc.2**

**Reproduction of the problem**
From a clean install, run the example project here: https://github.com/mucsi96/nightwatch-cucumber/tree/master/examples/simple-example

**What is the expected behavior?**
I am able to run the example and my step definitions execute

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **nightwatch-cucumber version:**
6.1.1

* **nightwatch version:**
0.9.11
* **cucumber version:**
2.0.0-rc.4

* **Node.js version:**
6.9.1

**Comment by mucsi96** [comment]
Thanks for reporting! I will check this out. Can I ask you to check with rc3?

**Comment by damitas** [comment]
Hi, rc3 works ok!  Thanks.

**Comment by mucsi96** [comment]
Hi @damitas! Now everything should work with the latest version. Please check the docs as a lot of things has changed
