### ISSUE TITLE
Can't make use of client in the Step definition file...

### ISSUE THREAD

**Issue by sharathkonda** [mucsi96/nightwatch-cucumber#17]
Hi Mucsi,
Hope you are doing good. Thanks for the integration with Nightwatch and Cucumber.
I am planning to make use of nightwatch page objects. In order to do so, I need to access the client in the step definition file.

Is there any way, where it understands the client object from the step definition?

Your help is very much appreciated.

Kind regards
Sharath Konda

**Comment by mucsi96** [comment]
Thanks for feedback! I added a sample usage to readme.
