### ISSUE TITLE
Return page object in step definitions does not work

### ISSUE THREAD

**Issue by kinyat** [mucsi96/nightwatch-cucumber#174]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
```

**Current behavior**
I followed the page object example but cannot get it work.
Stuck for a while and found a way to make it work.
My step won't work unless i return the client object instead of the page object
Not sure if only me has this issue.

**Expected/desired behavior**
It should follow the given page object example to use the returned page object instead of the client object. 

**Reproduction of the problem**
Original Problematic Code:
```javascript
import {client} from 'nightwatch-cucumber'
import {defineSupportCode} from 'cucumber'

defineSupportCode(({Given, Then, When}) => {
  Given(
    /^I am logged in as "([^"]*)" with password "([^"]*)"$/,
    (username, password) => {
      const loginPage = client.page.login()

      return loginPage
        .navigate()
        .waitForElementPresent('@username', 10000)
        .loginAs(username, password)
        .waitForElementPresent('body.logged-in', 10000)
    }
  )
})
```

Working Code:
```javascript
import {client} from 'nightwatch-cucumber'
import {defineSupportCode} from 'cucumber'

defineSupportCode(({Given, Then, When}) => {
  Given(
    /^I am logged in as "([^"]*)" with password "([^"]*)"$/,
    (username, password) => {
      const loginPage = client.page.login()

      loginPage
        .navigate()
        .waitForElementPresent('@username', 10000)
        .loginAs(username, password)
        .waitForElementPresent('body.logged-in', 10000)

      return client
    }
  )
})
```

**What is the expected behavior?**
The Original Problematic Code should work.

* **nightwatch-cucumber version:**
7.0.4

* **nightwatch version:**
0.9.11

* **cucumber version:**
2.0.0-rc.5

* **Node.js version:**
v6.5.0

**Comment by damitas** [comment]
I am having a similar issue.  I am running my tests with 
`nightwatch -e chrome`

The browser will not launch if I use the following: 

     Given(/^the application has loaded$/, () => {
        const login= client.page.login()
        return login
          .navigate()
          .waitForElementVisible('@body', 1000)
      })

      Then(/^I scroll the portal page$/, () => {
         const browse = client.pagenbrowse();  
          return browse
               .waitForElementVisible('@portal_arrow_next', 1000)           
              .click('@portal_arrow_next')            
      })


But works with this:

    Given(/^the application has loaded$/, () => {   
        const browse = client.page.login()
        return browse
          .navigate()
          .waitForElementVisible('@body', 1000)
      })

      Then(/^I scroll the portal page$/, () => {
         const browse = client.page.browse();  
          browse
           .waitForElementVisible('@portal_arrow_next', 1000)           
           .click('@portal_arrow_next')
            client.pause(1000)
         
      return client
      })

**Comment by damitas** [comment]
Also this step PASSES (when it should fail)

    Given(/^image is on the portal screen$/, () => {
      const browse = client.page.browse();
      
     return  browse          
      .expect.element('@cover_images').to.have.css('background-image').which.contains('url("http://fail_my_image.jpeg")');

  })

When I add `return client` the step fails as I expected.

     Given(/^image is on the portal screen$/, () => {
          const browse = client.page.browse();
      
     browse          
      .expect.element('@cover_images').to.have.css('background-image').which.contains('url("http://fail_my_image.jpeg")');

       return client
       })
