### ISSUE TITLE
Add an example with custom commands.

### ISSUE THREAD

**Issue by mucsi96** [mucsi96/nightwatch-cucumber#178]

**Comment by JonWallsten** [comment]
Is the syntax changed for custom commands as well with the 7.0.0 breaking changes?

**Comment by slashsorin** [comment]
@JonWallsten I can't figure out the custom commands part. Could you please describe how you did it and maybe post an example? Thanks! :)

**Comment by JonWallsten** [comment]
@slashsorin Actually the syntax for custom command hadn't changed. Only the step definition and other various implementation. Custom commands/assertions are still intact. Ask you question and provide all the details in the official Google group: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/nightwatch-cucumber
