### ISSUE TITLE
Add examples of how to implement junit and html reports in version 7.x.x

### ISSUE THREAD

**Issue by JonWallsten** [mucsi96/nightwatch-cucumber#179]
Would you mind creating examples of how to integrate cucumber-junit and cucumber-html-reporter?
It's not really crystal clear. Especially not the junit (writing in the support forum about it as we speak)

**Comment by myklt** [comment]
@JonWallsten ,

You can check how I use "cucumber-html-reporter" here: https://github.com/myklt/es6-mvb/blob/master/test/e2e/runner.js . A little bit hacky, but works as expected.

**Comment by JonWallsten** [comment]
Thanks! I'll check it out.

**Comment by kinyat** [comment]
I am using a custom script to generate the html report after run.
Because of the parallel runners, you do not want to generate the report in each runner so you will need to generate it outside of NightWatch.

**Comment by Geczy** [comment]
+1

**Comment by IvanNaumenko** [comment]
Hey, how to generate XML report from nightwatch - cucumber? I could try in for examples from http://mucsi96.github.io/nightwatch-cucumber/#junit-xml-reports
