### ISSUE TITLE
Nightwatch page object elements from step definitions

### ISSUE THREAD

**Issue by sharathkonda** [mucsi96/nightwatch-cucumber#18]
Hi Igor,

Do you have an example, where it access the nightwatch page objects and it's elements from the step definitions.

Kind regards
Sharath Konda

**Comment by sharathkonda** [comment]
Thanks Igor,

Was able to sort out the page objects after sending the email by referring, 
var pageObject = this.page.pageObjectFile()
Some reason was only able to refer to the elements by pageObject.elements.elementName.selector
but not by @elementName from past two days.

_______________________
step definition file:
____________
 var home = this.page.home();
        
        this.assert.visible(home.elements.username.selector);
  home.login(centreData.CO.username, centreData.CO.password);
        this.page.common().waitForLoaderToDisappear();
___________________________________


Page Object:
_____________

var page = {
    
    // page elements (allows @elementkey in tests)
    elements : {
        username    : { selector: 'input[id=usn]' },
        password    : { selector: 'input[id=pass]' },
        submit      : { selector: 'input[type=submit]' }
    },

    // functions to be exposes via the page object via this.page.scriptname().functionname()
    functions: {

        login: function(username, password){
            
            var common = this.api.page.common();
            
            // always return runtime as this allows chaining within the step methods  
            return common.waitForLoaderToDisappear()
                        .setValue(page.elements.username.selector, username)
                        .setValue(page.elements.password.selector, password)
                        .click(page.elements.submit.selector)
                        .waitForElementVisible(common.elements.logout.selector, 5000);
        }
    }
};

// export in a format nightwatch understands
module.exports = {
  
    // commands are exposed within step definition mehtod via this.page.home().functionName  
    commands: [page.functions],
    
    // elements selectors allow step definition to use @attributeName to action a selector rather
    // than hard coding selectors. For example this.setValue('@username','random-user'); 
    elements: page.elements
};

**Comment by mucsi96** [comment]
So if I am understanding you correctly the following code snippet is not working for you?

```
this.page.home().assert.visible('@username');
```

**Comment by sharathkonda** [comment]
Regarding

this.page.home().assert.visible('@username');

Its working, I was using this.assert.visible...rather than the
page_object.assert, hence the issue.

Cheers

Sharath Konda
