### ISSUE TITLE
subfolder group hierarchy for reports

### ISSUE THREAD

**Issue by AlfredoMoretta** [mucsi96/nightwatch-cucumber#184]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
report don't consider subfolder for group. if i've GroupFolder--
                                                                                                   |->folderTest1 ->test1.feature
                                                                                                   |->folderTest2 ->test2.feature
the report is all features togheter

**Expected/desired behavior**
is it possible to have hierarchy for the folder too in the reports folder?

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://c9.io, http://www.koding.com, https://www.nitrous.io or similar.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **nightwatch-cucumber version:** latest

* **nightwatch version:** latest

* **cucumber version:** latest

* **Node.js version:** 7.2.0

**Comment by mucsi96** [comment]
Thank you for the feedback! It is not possible to solve this in this package. This is a new feature for Cucumber.js JSON formatter. Currently it creates a flat structure. See https://github.com/cucumber/cucumber-js/blob/master/src/formatter/json_formatter.js Also it is not possible to create a folder hierarchy in reports folder as the report is a single json file. 

I am closing the issue as it could not be solved here.
