### ISSUE TITLE
Nightwatch "Expect" API assertions are not working 

### ISSUE THREAD

**Issue by myklt** [mucsi96/nightwatch-cucumber#185]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
The step using "Expect" assertions API always succeeds. 

**Expected/desired behavior**
The step using "Expect" assertions API should fail in case of not met condition.

**Reproduction of the problem**
```
Scenario: Home page greets politely
  Then the page should contain text "Hello World!"
 
Then(/^the page should contain text "(.*?)"$/, (text) => {
        return client.expect.element('body').text.to.contain(text);
}); 
```

**What is the expected behavior?**
Nightwatch "Expect" assertions API should work the same as "Assert" API

**What is the motivation / use case for changing the behavior?**
"Expect" API is very easy to use and favored by Nightwatch team.

**Please tell us about your environment:**

* **nightwatch-cucumber version:** 7.0.7

* **nightwatch version:** 0.9.12

* **cucumber version:** 2.0.0-rc.6

* **Node.js version:** 6.9.4

**Comment by mucsi96** [comment]
Hi @myklt ! I investigated the issue. And found the answer. Nightwatch assertions are designed to be used from inside a callback. They do not throw exceptions. Only set some flags. If you need a synchronous assertions which throws exceptions use https://github.com/mjackson/expect, http://chaijs.com/ or anything else. So this is not an issue => closing

**Comment by myklt** [comment]
Hi @mucsi96 ! 

I've investigated this issue as well. So you are right, that Nightwatch assertions do not throw exceptions. But the difference between "assert" and "expect" APIs is that the later does not return client's api (promisified one) after adding command to CommandQueue. 

Having in mind above findings, I was able to use below workaround:

```
Then(/^the page should contain text "(.*?)"$/, (text) => {
  return client.perform(() => {
    client.expect.element('body').text.to.contain(text);
  })
})
```

"perform" fits perfectly here because even in [Nightwatch API docs](http://nightwatchjs.org/api#perform) it is written that it:

> allows access to the "api" in a callback. Can be useful if you want to read variables set by other commands. 

On the other hand, it would be much better to have ability to assert using Expect API in some terser way. Before closing this issue, I will spend some more time on investigation whether I could come up with any  terser approach. If you have any ideas, please share.

Thanks!

**Comment by mucsi96** [comment]
Thanks @myklt !

**Comment by mucsi96** [comment]
Finally I could fix that. Released in `7.0.8`

**Comment by mucsi96** [comment]
Thanks for reporting this!

**Comment by myklt** [comment]
Hi @mucsi96 , thanks for the fix.

**Comment by myklt** [comment]
Hi @mucsi96 , I found one more issue related to the same expect api and raised a pull request. Could you please review it?
