### ISSUE TITLE
Epic bug with assert.ok

### ISSUE THREAD

**Issue by kerimovaa** [mucsi96/nightwatch-cucumber#186]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
The step using "client.assert.ok"  always succeeds.

**Expected/desired behavior**
The step using assertion API should fail in case of not met condition.

**Reproduction of the problem**
You can reproduce this problem if you write simple feature about the sum of numbers. 
Example: 
`Feature: test`

  `Scenario: testing `
   ` When i add 2 and 3 `
   ` Then i will get 6 `

Then we need write the step definition
`import {client} from 'nightwatch-cucumber';`
`import {defineSupportCode} from 'cucumber';`

`defineSupportCode(({Given, When, Then}) => {`
 ` let sum;`

 ` When(/^i add ([^"]*) and ([^"]*)$/, (num1, num2) => {`
   ` sum = num1 + num2;`
  `});`

  `Then(/^i will get ([^"]*)$/, (result) => {`
  `  client.assert.ok(result == sum);`
 `  });`
` });`

**What is the expected behavior?**
Expected behavior - i see a failure because 2 + 3 not equal 6 !
But i got this:
`Feature: test`

  `@testing`
  `Scenario: testing`
  `✔ When i add 2 and 3`
  `✔ Then i will get 6`

`1 scenario (1 passed)`
`2 steps (2 passed)`

**What is the motivation / use case for changing the behavior?**
Assert - one of the most important instruments for all testers. It must be work correctly.

**Please tell us about your environment:**

* **nightwatch-cucumber version: 7.0.7**

* **nightwatch version: 0.9.12**

* **cucumber version: 2.0.0-rc.6**

* **Node.js version: 6.3.1**

P.S. sorry for my english. I'm not a native english speaker.

**Comment by JonWallsten** [comment]
Have you checked the actual values of _result_ and _sum_ in your assert?
With a console log for example. I have a feeling the values are not what you think they are.

**Comment by kerimovaa** [comment]
Yep. 
```
Feature: test

  @testing
  Scenario: testing
  ✔ When i add 2 and 3
6 5
  ✔ Then i will get 6

1 scenario (1 passed)
2 steps (2 passed)
0m00.005s
```

**Comment by mucsi96** [comment]
Thank for the feedback! You need to add a return before client.assert to return a promise. Then cucumber will await its execution. This was a breaking change in version 7. Also you can use generators or async functions to await the promise and something else. Hope this helps

**Comment by kerimovaa** [comment]
I have added 'return' but i haven't still the failure 
import {client} from 'nightwatch-cucumber';
import {defineSupportCode} from 'cucumber';

```
defineSupportCode(({Given, When, Then}) => {
  let sum;

  When(/^i add (\d+) and (\d+)$/, (number1, number2) => {
    sum = number1 + number2;
  });

  Then(/^i will get (\d+)$/, (result) => {
    console.log(result,sum);
    return client.assert.ok(result == sum);
  });
});
```

```
@testing
Feature: test

  @testing
  Scenario: testing
  ✔ When i add 2 and 3
6 5
  ✔ Then i will get 6

1 scenario (1 passed)
2 steps (2 passed)
0m00.005s
```

**Comment by mucsi96** [comment]
Wow. Let me investigate that

**Comment by kerimovaa** [comment]
You will get the failure if you wrap assert in client.perform. Like this:
```
Then(/^i will get (\d+)$/, (result) => {
    console.log(result,sum);
    return client.perform( () => {
      client.assert.ok(result == sum);
    });
  });
```

And failure:
```
1) Scenario: testing - features/desktop/test.feature:4
   Step: Then i will get 6 - features/desktop/test.feature:6
   Step Definition: build/__e2e__/step_definitions/desktop/test.js:18
   Message:
     Failed [ok]: (false == true) - Expected "true" but got: "false"
         at F.<anonymous> (../../../../src/__e2e__/step_definitions/desktop/test.js:14:7)

1 scenario (1 failed)
2 steps (1 failed, 1 passed)
0m03.072s
```

**Comment by mucsi96** [comment]
Hi @kerimovaa! I investigated the issue. And found the answer. Nightwatch assertions are designed to be used from inside a callback. They do not throw exceptions. Only set some flags. If you need a synchronous assertion which throws exceptions https://github.com/mjackson/expect, http://chaijs.com/ or anything else. So this is not an issue => closing

**Comment by mucsi96** [comment]
Finally I could fix that. Released in `7.0.8`. Thanks for reporting this!

**Comment by kerimovaa** [comment]
Thanks!))

**Comment by kerimovaa** [comment]
Hi, @mucsi96  . I don't what happened but this bug is repeating again now. 
Nightwatch-cucumber : 7.0.9
```
Feature: test

  @testing
  Scenario: testing
  ✔ When i add 2 and 3
  ✔ Then i will get 6

1 scenario (1 passed)
2 steps (2 passed)
0m00.006s
Cucumber HTML report reports/1487070433/cucumber.html generated successfully.
JUnit report reports/1487070433/cucumber.xml generated successfully.
```

```
import {client} from 'nightwatch-cucumber';
import {defineSupportCode} from 'cucumber';

defineSupportCode(({Given, When, Then}) => {
  let sum;

When(/^i add ([^"]*) and ([^"]*)$/, (num1, num2) => {
  sum = num1 + num2;
});

Then(/^i will get ([^"]*)$/, (result) => {
    client.assert.ok(result == sum);
  });
});
```

Can you please investigate again ?

**Comment by mucsi96** [comment]
You miss a return before `client.assert.ok(result == sum);` :)

**Comment by kerimovaa** [comment]
Ooo, f..)) thanks. sorry
