### ISSUE TITLE
New epic bug with assert in combination with page object

### ISSUE THREAD

**Issue by kerimovaa** [mucsi96/nightwatch-cucumber#190]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
The step using `client.page.anyPage().section.anySection.assert.anyAssertion('@anyElement')` always succeeds. This bug repeats only if you use section in your page object. 

**Expected/desired behavior**
The step using assertion API should fail in case of not met condition.

**Reproduction of the problem**
You can reproduce this problem if you write simple feature about check if the element present on page. Fox example:
```
Feature: testing assertion: element present

  @test
  Scenario: Search block on yandex page
    Given Has opened yandex page
     Then user will see yandex search
```

Then we need write the step definition
```
import {client} from 'nightwatch-cucumber';
import {defineSupportCode} from 'cucumber';

defineSupportCode(({Given, When, Then}) => {

  Given(/^Has opened yandex page$/, () => {
    return client.url('http://yandex.ru')
  });

  Then(/^user will see yandex search$/, () => {
    return client.page.yandex().section.main.assert.elementPresent('@searchBar', 'search is not displayed');
  });
});
```

And last one - page object:
```
module.exports = {
  url: 'http://yandex.ru',
  sections: {
    main: {
      selector: 'div.container.rows',
      elements: {
      body: 'body',
      searchBar: 'divasas.search2__input'
      }
    }
  }
}
```

I deliberately made a mistake in searchBar element (`divasas` - is not html tag)

**What is the expected behavior?**
Expected behavior - i see a failure because `divasas` isn't existing.
But i got this:
```
Feature: testing assert element present

  @test
  Scenario: Search block on yandex page
  ✔ Given Has opened yandex page
  ✔ Then user will see yandex search

1 scenario (1 passed)
2 steps (2 passed)
0m06.348s
```

After investigation i found that you will get a failure if you don't use section in page object.
```
module.exports = {
   url: 'http://yandex.ru',
   elements: {
     body: 'body',
     searchBar: 'divasa.search2__input'
   }
}

```
In this case you will get a failure:
```
Message:
     search is not displayed - Expected "present" but got: "not present"
```

it turns out that our bug is related on `sections` in page object

**What is the motivation / use case for changing the behavior?**
Page objects must work be work correctly

**Please tell us about your environment:**

- nightwatch-cucumber version: 7.0.7
- nightwatch version: 0.9.12
- cucumber version: 2.0.0-rc.6
- Node.js version: 6.3.1

P.S. i can link my project for help https://yadi.sk/d/C6VW3mtJ3E5S6t

**Comment by mucsi96** [comment]
Fix released in `7.0.10`. Thank you!
