### ISSUE TITLE
Possibility to add Cucumber Arguments per feature file.

### ISSUE THREAD

**Issue by leipert** [mucsi96/nightwatch-cucumber#192]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**

Currently the cucumber arguments are defined [globally for all feature files](https://github.com/mucsi96/nightwatch-cucumber/blob/v7.0.10/lib/runner.js#L88-L93).

**Expected/desired behavior**

Possibility to define cucumber arguments for each feature file, maybe with a function:

```js

const path = require('path');

require('nightwatch-cucumber')({
    cucumberArgs: ({featureFile}) => {
    	const baseName = path.basename(featureFile, '.feature');
    	const stepDefinition = `features/step_definitions/${baseName}.js`;
    	return [
	        '--tags', tags,
	        '--require', stepDefinition,
	        '--require', 'support',
	        '--format', `json:reports/cucumber_result.json`,
	        'features',
    	],
    }
});
```
**What is the motivation / use case for changing the behavior?**

We have a growing catalog of feature files and step definitions.
Currently they are organized like this:

```
.
├── a.feature
├── b.feature
└── step_definitions
    ├── a.js
    ├── b.js
    └── common.js
```

Now we want only to load the steps `a.js` and `common.js` for `a.feature` and the equivalent for `b.feature`. Cucumber.js has no way to do this at the moment, and it seems like they are not gonna in the future: https://github.com/cucumber/cucumber-js/issues/748.

**Please tell us about your environment:**

* **nightwatch-cucumber version:** 7.0.7

* **nightwatch version:** 0.9.12

* **cucumber version:** 2.0.0-rc.7

* **Node.js version:** 7.9.4

**Comment by leipert** [comment]
PS: Our team would be happy to help with an implementation, if you'd like 👍

**Comment by mucsi96** [comment]
Hi @leipert! Sorry for so long response. I think the best place for this kind of feature is cucumber.js itself. I would like to keep this integration layer as thin as possible.

**Comment by leipert** [comment]
@mucsi96 The problem is, they are not going to:
https://github.com/cucumber/cucumber-js/issues/748
