### ISSUE TITLE
document for multiple assertions 

### ISSUE THREAD

**Issue by CarinaSemerdzhan** [mucsi96/nightwatch-cucumber#193]
E.g.

How to deal in this case

`
Given(/^Main billboard has a title and a subtitle$/, () => {
        const billboard = client.page.billboard();
        const main = billboard.section.main;

        main.expect.element('@title').to.be.present;
        main.expect.element('@subtitle').to.be.present;
    });`

**Comment by mucsi96** [comment]
Hi, just add a return before last statement and it should work

**Comment by CarinaSemerdzhan** [comment]
Thank you!

**Comment by mucsi96** [comment]
You are welcome!
