### ISSUE TITLE
Allow configurable paths for features and step-definitions

### ISSUE THREAD

**Issue by singhshashi** [mucsi96/nightwatch-cucumber#21]
I am using WebStorm as the IDE and one of its benefits is that it generates stubs for step definitions based on what I specify in the feature file. But these step definitions are generated in the folder step_definitions which is created as a subfolder within features folder. 

Right now, I am copying the generated stubs from features/step_definitions to step-definitions/ to use nightwatch-cucumber. Instead if the path for step-definitions and features were configurable, then individuals could just specify it as per their preferences. 

If you agree with this, I can take a shot at doing the necessary changes.

**Comment by mucsi96** [comment]
Can we discuss it on the chat? https://gitter.im/mucsi96/nightwatch-cucumber
