### ISSUE TITLE
--retires does not seems to work

### ISSUE THREAD

**Issue by kinyat** [mucsi96/nightwatch-cucumber#213]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
It is currently just ignoring the --retries option

**Expected/desired behavior**
It should retry for a certain number of times depending on the option value

**Reproduction of the problem**
node ./node_modules/.bin/nightwatch --retries 3

**What is the expected behavior?**
It should retry 3 times

**What is the motivation / use case for changing the behavior?**
Because tests are not reliable, sometimes we need to rerun a few times to make sure it is not a false alarm

**Please tell us about your environment:**

* **nightwatch-cucumber version:**
7.1.0

* **nightwatch version:**
0.9.14

* **cucumber version:**
2.0.0-rc.5

* **Node.js version:**
6.10

**Comment by mucsi96** [comment]
Hi @kinyat! Thanks for reporting it! Can you provide some help with fixing it? I am busy with my university thesis

**Comment by MathiasHeld** [comment]
+1

**Comment by mucsi96** [comment]
This issue is depends on CucumberJS issue: https://github.com/cucumber/cucumber-js/issues/727

**Comment by mucsi96** [comment]
Currently closing it. Please reopen if the Cucumber issue is resolved

**Comment by jain-neeeraj** [comment]
hi @mucsi96 ,

Development at cucumber JS is almost completed. When is the next release planned for us?

Link to PR at cucumberJS--> https://github.com/cucumber/cucumber-js/pull/1114

**Comment by mucsi96** [comment]
There's no release planned. But I can increase the peer dependency range if it still work with latest cucumberjs and do a release. This package is deprecated and not actively maintained. You should start about thinking about migrating away from it. I suggest checking nightwatch-api
