### ISSUE TITLE
Cannot attach to scenario

### ISSUE THREAD

**Issue by stevehipwell** [mucsi96/nightwatch-cucumber#217]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
Cannot attach data to the scenario in the `Before` function or `BeforeScenario` event. Also the documentation for the `Before` function refers to a `scenario` sometimes and a `scenarioResult` others, this needs clarifying.

**Expected/desired behavior**
To be able to attach to the `scenario`.

**Please tell us about your environment:**

* **nightwatch-cucumber version:** latest

* **nightwatch version:** latest

* **cucumber version:** latest

* **Node.js version:** lts

**Comment by mucsi96** [comment]
Hi @stevehipwell ! Thanks for reporting it! Can you help out with fixing it? I very busy right now with my university thesis

**Comment by stevehipwell** [comment]
@mucsi96 I've had a closer look at it seems like it's just the documentation that is incorrect. I'll take a look and see if I can create a pull request for this.

**Comment by mucsi96** [comment]
@stevehipwell Can you provide information what is not correct in the documentation and where should be fixed?
