### ISSUE TITLE
Can i run tests via groups just like tags

### ISSUE THREAD

**Issue by sanmaru** [mucsi96/nightwatch-cucumber#22]
is there any way i can run the tests based on groups just like tags.? Do you have any solution planned or can you give any idea how to achieve this? 

Thanks,
San

**Comment by mucsi96** [comment]
Thanks for your feedback!
From verison `0.6.2` you can group features by placing them in same sub-folder. [More details](https://github.com/mucsi96/nightwatch-cucumber#feature-groups)

**Comment by sanmaru** [comment]
Thank you for considering my request and adding the group feature to this framework. Appreciate it.
