### ISSUE TITLE
About doing set up on windows 7 or 10 machine

### ISSUE THREAD

**Issue by vaishalilambe** [mucsi96/nightwatch-cucumber#236]
Hi,
I wanted to do complete set up with night watch JS, cucumber and selenium web driver. Can you please provide me step by step procedure to do it? Please provide it today itself. Thank you. 
I gone through online material but still facing issues so want to make sure I have followed right things.

**Comment by mucsi96** [comment]
Hi @vaishalilambe!

Sorry currently I have no time to provide a very detailed step by step guide.
Can you share the steps you did. And what is the issue you are facing? Also please send me the created project setup in zip without including the `node_modules` folder
