### ISSUE TITLE
The new [require(\"nightwatch-cucumber\").path] config src location does not work

### ISSUE THREAD

**Issue by sanmaru** [mucsi96/nightwatch-cucumber#24]
Hi 
Thank you for working on my issues. After i have updated the package, I am not able to run the tests. 
![nightwatch-cucumber_config json_src issue](https://cloud.githubusercontent.com/assets/8145154/12381149/02974f0c-bd39-11e5-977e-b3409804ef16.png)

In earlier versions, the temp-tests was working but it was only copying unnecessary test folders. As you had mentioned, that you cannot read nightwatch-cli args, i was wondering how about reading the cli args via process.argv.

**Comment by mucsi96** [comment]
Thanks for your feedback!

It should be resolved in new version `0.6.7`
