### ISSUE TITLE
Tags not being respected in programmatical API

### ISSUE THREAD

**Issue by erikmellum** [mucsi96/nightwatch-cucumber#242]
First of all, thanks for building nightwatch cucumber. Incredibly useful project and easy to use. I think there may be an issue with the programmatical API and the way it looks at tags.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
```
nightwatch.runner({
  config: "./nightwatch.conf.js",
  //env: env,
  //filter: '',
  tag: "manual_move"
}, () => {
  console.log('done');
});
```

Runs all tags when it should only run the manual_move tag.

For reference, here is my nightwatch.conf.js:
```
const reporter = require('cucumber-html-reporter');
require('nightwatch-cucumber')({
  cucumberArgs: ['--require', 'hooks.js', '--require', 'timeout.js', '--require', './rosetta/features/step_definitions', '--format', 'pretty', '--format', 'json:rosetta/reports/cucumber.json',  'rosetta/features']
});
module.exports = {
  "globals_path": "./globals/globals.js",
  "selenium": {
    "start_process": false
  },
  "test_settings": {
    "default": {
      "selenium_port": 9515,
      "selenium_host": "localhost",
      "request_timeout_options": {
        "timeout": 600000,
        "retry_attempts": 0
      },
      "default_path_prefix": "",
      "end_session_on_fail": false,
      "globals": {
        "app": "rosetta",
        "timeoutAsync": 10000
      },
      "screenshots": {
        "enabled": false,
        "on_failure": false,
        "on_error": false,
        "path": "./rosetta/screenshots"
      },
      "desiredCapabilities": {
        "browserName": "chrome",
        "chromeOptions": {
          "binary": "../installers/darwin/rosettastage-integration/osx32/rosettastage-integration.app/Contents/MacOS/nwjs"
        },
        "acceptSslCerts": true
      }
    }
  },
  "output_folder": "./rosetta/reports",
  "custom_commands_path": [
    "./rosetta/custom",
    "./custom"
  ]
};
```
**Expected/desired behavior**
I would expect it to only run the tags I specify (manual_move in this case)

**Reproduction of the problem**
30 second bug demo video: [tags_bug.zip](https://github.com/mucsi96/nightwatch-cucumber/files/1112692/tags_bug.zip)

**Please tell us about your environment:**

* output of the following command from your project root `npm ls nightwatch cucumber nightwatch-cucumber && node --version`:

```
integration@1.0.0 /Users/erikmellum/go/src/github.com/emeraldsci/ecl/desktop/integration
├── cucumber@2.3.1 
├── nightwatch@0.9.16 
└── nightwatch-cucumber@7.1.9 

v7.7.3
```

**Comment by erikmellum** [comment]
Maybe also worth noting is that it was working when I was using: `node nightwatch.js --tag manual_move` instead of the programmatical API.

**Comment by mucsi96** [comment]
Hi @erikmellum! This is the best issue description a ever received. Very appreciate that! Unfortunately I will have time to debug this only after around July 8.

**Comment by erikmellum** [comment]
Glad to hear it @mucsi96. I'll try to look at it more when I get the chance. 

I followed the execution path:
`runner.js -> run -> this.nightwatchApi.addTestRunner(this.executeTestModules.bind(this)) -
> tags = this.getTags(this.nightwatchApi.nightwatchArgv).concat(this.getSkipTags(this.nightwatchApi.nightwatchArgv))`

And tags looked correct up to that point. I haven't verified that with console output, and I stopped digging at that point in case I was missing something really stupid and obvious.

If I find anything else out I'll let you know.

**Comment by erikmellum** [comment]
Looks like these are the adjustedArgs from cucumber-api:
```
['--require',
  'hooks.js',
  '--require',
  'timeout.js',
  '--require',
  './rosetta/features/step_definitions',
  '--format',
  'pretty',
  '--format',
  'json:rosetta/reports/cucumber.json',
  '--tags',
  '@manual_move',
  '--tags',
  'not @wip',
  '--tags',
  'not @undefined',
  'rosetta/features/control_protocol.feature',
  'rosetta/features/install.feature',
  'rosetta/features/manual_move.feature' ]
```

Going to look a little deeper into it.

**Comment by erikmellum** [comment]
As far as I can tell nightwatch cucumber is passing everything correctly. 

https://docs.cucumber.io/tag-expressions/

**Comment by erikmellum** [comment]
Looks like this is the culprit. Shouldn't be a big change. I'll put in a PR. 
### Migrating from old style tags
```
--tags @dev stays the same
--tags ~@dev becomes --tags 'not @dev'
--tags @foo,@bar becomes --tags '@foo or @bar'
--tags @foo --tags @bar becomes --tags '@foo and bar'
--tags ~@foo --tags @bar,@zap becomes --tags 'not @foo and (@bar or @zap)'
```

**Comment by mucsi96** [comment]
Can you check #170 ?

**Comment by erikmellum** [comment]
Yep that is the issue I was having. My script was pushing "wip" onto the skiptags argument and so it made it appear as though the ones I was passing through the CLI were being ignored. In reality it was just only taking the last --tag.

I'll take a look at that PR today.

**Comment by erikmellum** [comment]
It seems like that PR is a little overcomplicated for this bug (at least to me). Maybe I just don't fully understand.

1. Not sure why we need to adjust the nightwatch args at all. It seems like we _only_ need to update args for the cucumber side
2. Not sure why the tags are being joined with an `or` instead of `and`. `and` is what this code used to do, and thats the functionality I'd imagine is more useful, and most people expect. It's definitely what I want.

I threw together a PR that shows how I fixed it on my fork. Let me know what you think.

https://github.com/mucsi96/nightwatch-cucumber/pull/243

**Comment by mucsi96** [comment]
This should be working now from version 7.2.0
