### ISSUE TITLE
Selenium process takes 1 minute to finish

### ISSUE THREAD

**Issue by gus4no** [mucsi96/nightwatch-cucumber#25]
Hi, this is probably unrelated to this, I'm not sure but.... any help appreciated.

Currently my scenario only tests an element being visible and even though the assertion succeeds, after 1 minutes and I get a `[Error: Step timed out after 60000 milliseconds]` and then the selenium process finishes.

**Comment by mucsi96** [comment]
Thanks for feedback!

**Comment by mucsi96** [comment]
Can you help me with sending the following?
- Sample project where timeout occurs
- Your OS name and version
- Version of nightwatch-cucumber, nightwatch and cucumber modules

**Comment by gus4no** [comment]
Thanks for the quick response, so this is the cucumber feature.

```
Feature: ROP chart
  As a User
  I want to see the ROP chart
  of my rings and wells

  Scenario: Rate of penetration chart
    Given I log in
      And I go to the "dashboard" page
```

Steps:

```

var paths = require('./paths.js');

module.exports = function(){
  this.Given(/^I log in$/, function () {
    // Write code here that turns the phrase above into concrete actions
    this.url(paths.urlFor('login')).waitForElementVisible('div#login', 1000);
    this.setValue('input#username', 'foo');
    this.setValue('input#password', 'bar');
    this.click('button#signin');
    this.assert.elementPresent('dl#user');
  });

  this.Given(/^I go to the "([^"]*)" page$/, function (page, callback) {
    // Write code here that turns the phrase above into concrete actions
    var path = paths.urlFor(page);
    this.url(path);
  });
```

and this is the outcome

![screenshot](https://www.evernote.com/l/AKe7Q3ktxGxIzrNJ1lzvjObnt2c5FXApqa0B/image.png)

Notice how the assertions finish in 21 seconds but the terminal keeps frozen for another minute, and then the selenium process finishes after that with that timeout error.

**Comment by mucsi96** [comment]
You need yo call the callback.
```
  this.Given(/^I go to the "([^"]*)" page$/, function (page, callback) {
    // Write code here that turns the phrase above into concrete actions
    var path = paths.urlFor(page);
    this.url(path);
    callback();
  });
```
Can I close this issue?

**Comment by gus4no** [comment]
yes, thanks for the help!
