### ISSUE TITLE
[Feature] Generate step definition from a .feature file

### ISSUE THREAD

**Issue by Frankusky** [mucsi96/nightwatch-cucumber#253]
Actually im generating my steps definition manually. It would be nice that you integrate a tool that generates the steps definitions from a .feature file. For example:
```
Feature: Google Search

Scenario: Searching Google

  Given I open Google's search page
  Then the title is "Google"
    And the Google search form exists
```

Should output a file like this:
```
const {defineSupportCode} = require('cucumber');

defineSupportCode(({Given, Then, When}) => {
	Given(/^I open Google's search page$/, () => {
		//Do something
	});

	Then(/^the title is "([^"]*)"$/, (title) => {
		//Do something
	});

	Then(/^the Google search form exists$/, () => {
		//Do something
	});
});
```
When we have scenarios outlines, it should generate the generic function with the regex instead of generating N functions with each value

**Comment by mucsi96** [comment]
Hello! Very nice idea. But this feature is mostly related to cucumberjs itself. Can you open this issue there? Closing for now
