### ISSUE TITLE
Always empty html testing localhost

### ISSUE THREAD

**Issue by Geczy** [mucsi96/nightwatch-cucumber#263]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
Localhost is empty

```
    await client.url(client.launch_url)
    await client.waitForElementVisible('body', 3000)

...

    await client.source(result => {
      console.log(result)
    })
```

```
{ sessionId: 'e80e8180-8124-11e7-9401-8b9e3e9fcd74',
  status: 0,
  value: '<html><head></head><body></body></html>' }
```

```
  test_settings: {
    default: {
      launch_url: 'https://127.0.0.1',
      selenium_port: 4444,
      selenium_host: '127.0.0.1',
      desiredCapabilities: {
        browserName: 'phantomjs',
        javascriptEnabled: true,
        acceptSslCerts: true,
        'phantomjs.binary.path': phantomjs.path,
      },
    },
```

launch_url is https on port 443

If I change launch_url to `https://github.com` it work's fine

**Expected/desired behavior**
Produce HTML of localhost server running port 443

**Please tell us about your environment:**

* output of the following command from your project root `npm ls nightwatch cucumber nightwatch-cucumber && node --version`

```
├── cucumber@2.3.1 
├── nightwatch@0.9.16 
└── nightwatch-cucumber@7.2.0 

v7.10.0
```

**Comment by Geczy** [comment]
If I switch to using Chrome it works

```
    chrome: {
      desiredCapabilities: {
        browserName: 'chrome',
        javascriptEnabled: true,
        acceptSslCerts: true,
      },
      selenium: {
        cli_args: {
          'webdriver.chrome.driver': chromedriver.path,
        },
      },
    },
```

**Comment by mucsi96** [comment]
Hello @Geczy! Thanks for you feedback! 

Unfortunately I cannot help based on information you provided. I need a minimal dummy project where I can reproduce and debug the issue. Please attach it as zip archive without including the `node_modules` folder. Also I would like you to check the same tests with pure Nightwatch, without using nightwatch-cucumber to narrow down the root cause of the issue.

**Comment by mucsi96** [comment]
I am closing this because of no response

**Comment by ignaciosagredo96** [comment]
In the file hooks.js replace this line:

 Before(() => {
    client
      .init('http://localhost')
      .maximizeWindow()
  })

For this:

 Before(() => {
    client
      .maximizeWindow()
  })
