### ISSUE TITLE
TypeError: Cannot read property 'getLineNumber' of undefined

### ISSUE THREAD

**Issue by mariarodrigu** [mucsi96/nightwatch-cucumber#267]
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use 

**Current behavior**

> Running:  super_
> TypeError: Cannot read property 'getLineNumber' of undefined
>     at getDefinitionLineAndUri (/Users/mariarodrigu/random/demo_cucumber/node_modules/cucumber/lib/support_code_library/helpers.js:98:24)
>     at /Users/mariarodrigu/random/demo_cucumber/node_modules/cucumber/lib/support_code_library/helpers.js:81:34
>     at defineSupportCode (/Users/mariarodrigu/random/demo_cucumber/features/step_definitions/google.js:7:3)
>     at /Users/mariarodrigu/random/demo_cucumber/node_modules/cucumber/lib/support_code_library/builder.js:77:12
>     at Array.forEach (native)
>     at Object.build (/Users/mariarodrigu/random/demo_cucumber/node_modules/cucumber/lib/support_code_library/builder.js:76:7)
>     at Cli.getSupportCodeLibrary (/Users/mariarodrigu/random/demo_cucumber/node_modules/cucumber/lib/cli/index.js:137:32)
>     at Cli.<anonymous> (/Users/mariarodrigu/random/demo_cucumber/node_modules/cucumber/lib/cli/index.js:144:39)
>     at next (native)
>     at tryCatcher (/Users/mariarodrigu/random/demo_cucumber/node_modules/bluebird/js/release/util.js:16:23)
>     at PromiseSpawn._promiseFulfilled (/Users/mariarodrigu/random/demo_cucumber/node_modules/bluebird/js/release/generators.js:97:49)
>     at Promise._settlePromise (/Users/mariarodrigu/random/demo_cucumber/node_modules/bluebird/js/release/promise.js:574:26)
>     at Promise._settlePromise0 (/Users/mariarodrigu/random/demo_cucumber/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise._settlePromises (/Users/mariarodrigu/random/demo_cucumber/node_modules/bluebird/js/release/promise.js:693:18)
>     at Async._drainQueue (/Users/mariarodrigu/random/demo_cucumber/node_modules/bluebird/js/release/async.js:133:16)
>     at Async._drainQueues (/Users/mariarodrigu/random/demo_cucumber/node_modules/bluebird/js/release/async.js:143:10)
> ARAR025648:demo_cucumber mariarodrigu$ node_modules/.bin/nightwatch
>

I'm having some problems trying to execute the [example of Google with Nightwatch and Cucumber](https://github.com/mucsi96/nightwatch-cucumber).
The test executes successfully but right after it finishes, a new blank driver instance is opened and the message above is displayed
We tried in 2 different machines but still found the same problem, even when executing some of the examples [https://github.com/mucsi96/nightwatch-cucumber/tree/master/examples](here)

**Expected/desired behavior**
Run without any kind of error

**Reproduction of the problem**
Just follow the 4 steps of installation and the demo

**Please tell us about your environment:**

- **OS**: MacOS Sierra
- **cucumber**: "^2.3.0"
- **nightwatch**: "^0.9.16"
- **nightwatch-cucumber**: "^7.2.0"
- **selenium-standalone**: "^5.8.0"

* output of the following command from your project root `npm ls nightwatch cucumber nightwatch-cucumber && node --version`
├── cucumber@2.3.1 
├── nightwatch@0.9.16 
└── nightwatch-cucumber@7.3.1 

v6.9.1

Thanks!

**Comment by gared1212** [comment]
Same Error always that my scenarios finish I got:

`TypeError: Cannot read property 'getLineNumber' of undefined
    at getDefinitionLineAndUri (project-ui/node_modules/cucumber/lib/support_code_library/helpers.js:98:24)
    at project-ui/node_modules/cucumber/lib/support_code_library/helpers.js:81:34
    at defineSupportCode (project-ui/features/step_definitions/steps.js:9:2)
    at project-ui/node_modules/cucumber/lib/support_code_library/builder.js:77:12
    at Array.forEach (native)
    at Object.build (project-ui/node_modules/cucumber/lib/support_code_library/builder.js:76:7)
    at Cli.getSupportCodeLibrary (project-ui/node_modules/cucumber/lib/cli/index.js:137:32)
    at Cli.<anonymous> (project-ui/node_modules/cucumber/lib/cli/index.js:144:39)
    at next (native)
`

**Comment by mucsi96** [comment]
Hi @mariarodrigu and @gared1212! I was not able to reproduce the issue with latest version. I have created an example [repo](https://github.com/mucsi96/nightwatch-cucumber-example). Can you check it?

**Comment by gared1212** [comment]
Hi @music

**Comment by gared1212** [comment]
Hi sir! It worked correctly what I saw is I had a different version of the selenium server  👍🏻
