### ISSUE TITLE
Support for Chrome Puppeteer 

### ISSUE THREAD

**Issue by Geczy** [mucsi96/nightwatch-cucumber#268]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```
How can we implement support for https://github.com/GoogleChrome/puppeteer ?

**Comment by mucsi96** [comment]
Chrome Puppeteer is not an implementation of the Web Driver protocol. Because of that it cannot be driven by Nightwatch. See: https://github.com/GoogleChrome/puppeteer#q-what-is-the-difference-between-puppeteer-selenium--webdriver-and-phantomjs
So it is not really possible here
