### ISSUE TITLE
Cucumber report generation with Cucumber 3 after test execution

### ISSUE THREAD

**Issue by GRme** [mucsi96/nightwatch-cucumber#274]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[x] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

Until `Nightwatch-Cucumber@7.3.1` the framework used `Cucumber 2` and I realized my Cucumber report generation in a hook with an `Event Handler`, like:

```
const reporter = require("cucumber-html-reporter");

defineSupportCode(function({ registerHandler }) {
  registerHandler("AfterFeature", function(features, callback) {
    try {
      var options = {
        theme: "bootstrap",
        jsonFile: "./reports/json_result/cucumber.json",
        output: "./reports/json_result/cucumber_report.html",
        reportSuiteAsScenarios: true,
        launchReport: false,
        metadata: {
          "App Version": "0.0.3"
       }
     };
     reporter.generate(options);
    } catch (e) {
      console.log(
        "Report generation is not possible with the following message:"
      );
      console.log(e);
    }

    client.end();
    callback();
  });
});
```

But since `Cucumber 3` the `Event Handler` isn't available anymore. Now I want to use `AfterAll` function, but the content of cucumber json report isn't generated at the time of executing the `AfterAll` function. So I get exception `reports/json_result/cucumber.json: Unexpected end of JSON input`, because the cucumber json file is empty at this time. How can I generate a Cucumber report after test execution in something like a `AfterAll` for a tear down. 

Here is my current code:
```
const reporter = require("cucumber-html-reporter");

defineSupportCode(function({ AfterAll }) {
  AfterAll(function(callback) {
    try {
      var options = {
        theme: "bootstrap",
        jsonFile: "./reports/json_result/cucumber.json",
        output: "./reports/json_result/cucumber_report.html",
        reportSuiteAsScenarios: true,
        launchReport: false,
        metadata: {
          "App Version": "0.0.3"
       }
     };
     reporter.generate(options);
    } catch (e) {
      console.log(
        "Report generation is not possible with the following message:"
      );
      console.log(e);
    }

    client.end();
    callback();
  });
});
```

THX Martin

**Comment by mucsi96** [comment]
Hi @GRme! Thanks for your feedback! I am happy to hear that you have upgraded to the latest version. 
There are some issue related to this topic. See:
https://github.com/cucumber/cucumber-js/issues/918
https://github.com/cucumber/cucumber-js/issues/890

So if you run nightwatch using `test` npm script then I suggest to use `posttest` npm script to generate a HTML report from JSON. You need to have a separate node.js script for that.

As I have time I will add an example to the documentation.

**Comment by GRme** [comment]
@mucsi96 
That was the right tip :) THX!!!
