### ISSUE TITLE
eventHandlers missing, unable to handle scenario and scenario-tags

### ISSUE THREAD

**Issue by slashsorin** [mucsi96/nightwatch-cucumber#275]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**

It seems that the eventHandlers are missing since added Cucumber 3 support. Is there any plan that they will be back?

**Expected/desired behavior**

Before, it was possible to do something like this:

registerHandler('BeforeScenario', scenario => {
        console.log(scenario.tags);
        ...
});

OR:

registerHandler('BeforeStep', () => {
       ...
});

**Comment by mucsi96** [comment]
Hello @slashsorin! eventHandlers were removed from [CucumberJS vesrion 3](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#300-2017-08-08). Use BeforeAll / AfterAll for setup code. Or Before / After for running code before / after scenario execution.

**Comment by slashsorin** [comment]
Hi @mucsi96! My problem here is that I can't access the scenario tags in the Before hook. For example, we have many test scenarios and we would like to run them in parallel, also, our application requires to be login for the tests to run. Running in parallel using the same login won't work, there will be no test isolation.

Here is a glimpse of what I mean:

Feature: feature name 1

  Background: Login before scenario starts
    When I do something on the page

  @login_info_usename_password
  Scenario: scenario name 1
    When I do something else on the page
    ...............



And in the eventHandlers we use to do:

const { defineSupportCode } = require('cucumber');
const { client } = require('nightwatch-cucumber');

defineSupportCode(({ registerHandler }) => {
    registerHandler('BeforeScenario', scenario => {
        //  here we get to access the values of the tags and have them available
        const loginInfo = scenario.tags[0].name.split('_');
        client.login(loginInfo[2], loginInfo[3]);
    });
});


Do you have any idea how cand this be done now? Btw, using anything from here: https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md doesn't work and there is no example where the parameter in the Before hook is 'scenario'.

Thanks!
