### ISSUE TITLE
Control Load and Execution .features files

### ISSUE THREAD

**Issue by rpereira15** [mucsi96/nightwatch-cucumber#277]
** I'm sending to ... ** (check one with "x")

Error report
[x] feature request
[] support request => Please do not send support request here, use https://groups.google.com/d/forum/nightwatch-cucumber

** Current Behavior **
Cucumber uploads all .features files in alphabetical order. This behavior limits our control over tests of runs and forces to write the whole scenario into a unic .feature file.

** E fileed / Desired Behavior **
To control the order of execution of .features files, I implemented this behavior in the project example.
You can see it at [here](https://github.com/rpereira15/cucumber) what i propose.
Here is new feature. [workflow.zip](https://github.com/mucsi96/nightwatch-cucumber/files/1271330/workflow.zip)

The "getFeatureFiles" method in cucumber-api.js has been modified.
After that, I can pass a new cucumber parameter called --feature in nightwatch.conf.js and after an array with directories I want to load first.

** What is the expected behavior? **
With this control behavior, we will write much less .feature files. Since we can reuse between one test and another, just set the order.
In addition, the testing project will be much more organized. We can apply concepts like single responsibility and others.

** What is the case of motivation / use to change behavior? **
My need at work. Every time the workflow changes, I need to edit my .feature files.

* output the following command from your root project `npm ls nightwatch cucumber nightwatch-cucumber && node --version`

+ - cucumber@3.0.1
+ - nightwatch@0.9.16
`- nightwatch-cucumber@8.0.5

**Comment by mucsi96** [comment]
Hi @rpereira15! Thanks for the feature idea! This should be implemented as part of CucumberJS. The goal of this package is to provide the best possible integration between Nightwatch and CucumberJS. 
I have no capacity to maintain extra features which does not exist in Nightwatch or CucumberJS.
So I suggest to submit a pull request in CucumberJS.
