### ISSUE TITLE
After a scenario failure, cucumber-nightwatch stops running the remaining scenarios 

### ISSUE THREAD

**Issue by sharathkonda** [mucsi96/nightwatch-cucumber#28]
I got 5 scenarios in a feature.

If the 3rd scenario is failed, the runner stops and doesnt' continue to execute the remaining scenarios in that feature file.

**Comment by mucsi96** [comment]
Thanks for feedback!

This is the expected behavior. See Nightwatch.js [assertions](http://nightwatchjs.org/api#assertions)
Can I close this issue?

**Comment by ivancho98** [comment]
Actually, it is possible that @sharathkonda is using .verify, in that case the runner should not stop.

**Comment by mucsi96** [comment]
@sharathkonda are you using `.verify` for assertions?

**Comment by sharathkonda** [comment]
I use in my common library the nightwatch assertion.

this.api.assert.visible(selector);

**Comment by mucsi96** [comment]
Try to replace `assert` with `verify`. This way when an assertion fails, the test logs the failure and continues with other assertions.

**Comment by rohitkashyapvatta** [comment]
This is happening in our case as well, the test step failure , fails the other scenarios of the suite with same error  "at World.<anonymous> (/home/jenkins/workspace/.............................)" . Can you please advise what is happening here?

**Comment by JthenG9** [comment]
I am seeing the same as well, using : `client.verify.elementPresent(elements)` within a loop, stops once it fails and does not continue with the rest of the elements in the loop.
