### ISSUE TITLE
Nightwatch-cucumber doesn't work with cucumber 3.0.3

### ISSUE THREAD

**Issue by stevehipwell** [mucsi96/nightwatch-cucumber#288]
**I'm submitting a bug report** 

**Current behavior**
Running _cucumber-nightwatch_ throws an error.

**Expected/desired behavior**
No error being thrown.

**Reproduction of the problem**
Use _cucumber 3.0.3_.

**Cause**
Line 10 of _cucumber-api.js_ references **cucumber/lib/runtime/attachment_manager/attachment** and this file has been moved.

**Comment by themanifold** [comment]
I've just started seeing this behaviour too, with cucumber 3.0.3

**Comment by mucsi96** [comment]
@stevehipwell @themanifold Thanks for reporting! This should be ok now with version `8.2.2`
