### ISSUE TITLE
Running scenario outlines with 

### ISSUE THREAD

**Issue by ivancho98** [mucsi96/nightwatch-cucumber#29]
I am trying to run a scenario outline like in https://github.com/cucumber/cucumber/wiki/scenario-outlines,
but when run with nightwatch only the last line is actually run.

**Comment by mucsi96** [comment]
Thanks for feedback!
I will check it

**Comment by sharathkonda** [comment]
I think nightwatch-cucumber is not supporting scenario-outline as it is
taking only the last row.

**Comment by mucsi96** [comment]
nightwatch-cucumber is supporting scenario outlines from version `1.2.0`.
Thanks for feedback!
