### ISSUE TITLE
ERROR Error: Feature source features doesn't exists at featureFiles.map.forEach nightwatch cucumber

### ISSUE THREAD

**Issue by JaspreetBamrah** [mucsi96/nightwatch-cucumber#306]
Hello,

I am integrating nightwatch-cucumber with nodejs and created the following file structure:
<img width="233" alt="screen shot 2017-10-26 at 2 24 45 pm" src="https://user-images.githubusercontent.com/28526196/32033659-793f7228-ba59-11e7-8a19-48d8ee0ed655.png">

**In my nightwatch.conf.js** I have:
var seleniumServer = require('selenium-server')
var nightwatchCucumber = require('nightwatch-cucumber')

var nightwatchCucumberConf = {
    runner: 'nightwatch',
    featureFiles: '../tests/features/',
    stepDefinitions: '../tests/features/step_definitions/',
    closeSession: 'afterFeature'
}
module.exports = { 
...
}
**In package.json:**
"scripts": {
    "hip": "nightwatch --config nightwatch.conf.js --env chrome"
  },

but when I run npm run hip it gives me following error:

> ERROR Error: Feature source features doesn't exists
>     at featureFiles.map.forEach (/Users/jaspreet/Desktop/new/node_modules/nightwatch-cucumber/lib/runner.js:166:17)
>     at Array.forEach (native)
>     at Runner.run ...............................32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at CliRunner.readSettings (/Users/jaspreet/Desktop/Jazz/Official/hip-new/node_modules/nightwatch/lib/runner/cli/clirunner.js:87:23)
>     at CliRunner.setup (/Users/jaspreet/Desktop/Jazz/Official/hip-new/node_modules/nightwatch/lib/runner/cli/clirunner.js:48:8)
>     at Object.exports.runner (/Users/jaspreet/Desktop/Jazz/Official/hip-new/node_modules/nightwatch/lib/index.js:551:17)
>     at /Users/jaspreet/new/node_modules/nightwatch/bin/runner.js:10:16
> There was an error while starting the test runner:

Can you guide me please.

**Comment by mucsi96** [comment]
Hi @JaspreetBamrah! Thanks fro reporting! Your configuration looks very outdated. Please check the https://github.com/mucsi96/nightwatch-cucumber-example repository for a more updated configuration.
