### ISSUE TITLE
When running all tests scope by npm-run-all if one test dropped - the subsequent tests are skipped

### ISSUE THREAD

**Issue by IvanNaumenko** [mucsi96/nightwatch-cucumber#308]
[ x] bug report

Hello

I have the next problem
When I run tests by npm-run-all, if one test dropped - the subsequent tests are skipped. I experemented with
 end_session_on_fail: true,
 skip_testcases_on_fail: true,

and it hasn't helped too.

When test has the success result - all fine: session closed, and another test is running. Next test starts on the previous dropped page, only page updated after started the new one. New test in beginning from start step on the dropped page, doesn't find it and dropped, and so on. That behavior I got only with fail tests. I need when test is dropped - it should be close browser and next test will start.
And it's very critical moment. all project will build on nightwatch-cucumber...

I run by script 

npm run test

 "test": "npm-run-all start report --continue-on-error"
  "start": "nightwatch",
  "report": "node reporter.js"

"cucumber": "^3.1.0",
 "nightwatch": "^0.9.16",
 "nightwatch-cucumber": "^8.2.8"

  abortOnAssertionFailure: false,

Please, any advise or fixes...anything will help. 

![hooks](https://user-images.githubusercontent.com/32741530/32215490-ba430800-be2a-11e7-9c4f-bb9c0cf314a4.jpg)

![fail](https://user-images.githubusercontent.com/32741530/32228679-8d5c829e-be57-11e7-8852-3c648c7d6478.jpg)

**Comment by mucsi96** [comment]
Solved with the following hook:
```
const { client } = require('nightwatch-cucumber');
const { defineSupportCode } = require('cucumber');

defineSupportCode(({ After }) => {
    After(() => client.deleteCookies().refresh());
});
```
