### ISSUE TITLE
Feature request:

### ISSUE THREAD

**Issue by alex-chen-bridg** [mucsi96/nightwatch-cucumber#352]
I want to put additional information into the cucumber.json reporting file.  I don't know that there is a way to do this.  In other reporting tools, there is a "context" (not web element context, but test context) that allows you to add additional information to xml, json, or whatever other output the tool is in.   Something like:

[[this.context.add("This test took 20 minutes from the time it started") // in before, beforeEach, afterEach etc.]]

would show up in the xml/junit/whatever report.

**Comment by mucsi96** [comment]
Hi @alex-chen-bridg! Thanks for feedback! I fully agree with having such feature. I suggest to submit an issue/PR for CucumberJS itself. I do not plan to add extra features in this package on top of Nightwatch and Cucumber ones
