### ISSUE TITLE
Start test suite using cucumber-js

### ISSUE THREAD

**Issue by rafenden** [mucsi96/nightwatch-cucumber#419]
I would like to start my tests using the `cucumber-js` command, same way as it's done in [nightwatch-api](https://github.com/mucsi96/nightwatch-api).

Is this currently possible?

**Comment by spnraju** [comment]
Hello @rafenden It is nor possible with this package. Infact, that is the reason nightwatch-api has come into existence. Please close the issue if it answers your question.

**Comment by rafenden** [comment]
It does, thank you.
