### ISSUE TITLE
The launch of test scope is not working from v 2.1.1 

### ISSUE THREAD

**Issue by VolhaHubava** [mucsi96/nightwatch-cucumber#53]
Steps to reproduce:
1. I have a version 2.1.1 and latest of nightwatch-cucumber
2. I have a few feature files which have the same tag.
3. I try to launch tests using this tag
4. The first test from the first feature file is working fine

expected result: the second test from the second feature file will be launched
actual result: it's failed with error (see screenshot)

Note: it works fine till the ver 2.1.1

![b9b4962c606d25240b4b8cd16dbcfeb1](https://cloud.githubusercontent.com/assets/7341289/14492199/6f8b310a-0186-11e6-9cb5-b820053ed77b.png)

**Comment by mucsi96** [comment]
Thanks for you feedback!
I will check it

**Comment by mucsi96** [comment]
@VolhaHubava I was not able to reproduce the issue with provided steps using latest nightwatch-cucumber version. I extended the already existing   tag test (https://github.com/mucsi96/nightwatch-cucumber/tree/fix-tag-filtering/test/nightwatch-tag-test) by adding the same tag for both feature files. But both feature files succeed. Can you provide a simple sandbox for reproducing this issue?

**Comment by VolhaHubava** [comment]
The last release #2.1.7 helped. Thanks

**Comment by mucsi96** [comment]
Cool!:)
