### ISSUE TITLE
Second scenario not running when session closes after scenario

### ISSUE THREAD

**Issue by AlexMurphy** [mucsi96/nightwatch-cucumber#54]
After changing `closeSession: 'afterFeature'` to `closeSession: 'afterScenario'` in index.js the second scenario in the feature file doesn't run. 

![myscreenshot](https://cloud.githubusercontent.com/assets/6222298/14557795/dead1fa0-02f6-11e6-9710-bdc8a0f3154f.png)

This issue can be reproduced with the demo feature.

**Comment by mucsi96** [comment]
Thanks for you feedback!
I will check it

**Comment by mucsi96** [comment]
A fix is released in version `2.1.7`. Thanks for reporting the issue!
