### ISSUE TITLE
Not running multiple features

### ISSUE THREAD

**Issue by lcbotha** [mucsi96/nightwatch-cucumber#6]
I can't seem to get multiple features to run using this example. I've tried passing in tags to cucumber using the following code but it still doesn't work.

```javascript
runtime = Cucumber(getFeatureSources(), getSupportCodeInitializer(), {tags: ["@testplan"]});
```

Not sure what's the problem?

**Comment by mucsi96** [comment]
Thanks for reporting.
I will check it.

**Comment by lcbotha** [comment]
Hi, just want to follow up if you have had a chance to take a look at this issue. I'm not sure if the issue lies with your implementation or with cucumber-js.

It looks like when the runtime.getFeatures().getFeatures().forEach function is called, only one feature is returned and not all of them.

Should cucumber be processing all features by default or will it only process the first one unless tags are specified?

**Comment by untoldwind** [comment]
There is just a call to next missing at the end of the forEach callback:

Sorry, it's to late to create a proper pull request, so here's my code-chunk that seems to be working as intended:
```javascript
runtime.getFeatures().getFeatures().forEach(function (feature, next) {
    createTestFile(feature);
    feature.instructVisitorToVisitScenarios({
        visitScenario: function (scenario) {
            var steps = [];
            scenario.getSteps().forEach(function (step, next) {
                var stepExecutor = getStepExecutor(step);

                if (stepExecutor) {
                    steps.push(stepExecutor);
                }
                next();
            }, function () {
                discoverScenario(feature, scenario, steps);
            });
        }
    });
    next(); // <--- that's the one
}, function () {
});
````

**Comment by sharathkonda** [comment]
Thanks for the solution.
Last time when I tried, it was taking only one scenario  of that one feature.
Do you think there should be next()  just before the end of the feature.instruct....funtion.

**Comment by mucsi96** [comment]
Thanks for the solution!

**Comment by rsachin123** [comment]
Hi,
i have two feature file
file 1:- @login, @sprint 6 
feaute file:---fdasf-dasf-ad-f-fsdf
scenario:-jklsdfjldkjf

file 2:- @lcbotha  @ sprint 7
feaute file:---fdasf-dasf-ad-f-fsdf
scenario:-jklsdfjldkjf

Query:-
i want to execute first sprint 6 test cases and after that sprint 7 test cases

Now i am using the comment in json file like "start:eggo":"npm run start -- --tags @sprint6, @sprint7"
But it is nto working
Please help me
