### ISSUE TITLE
Scenario steps are printed in the console repeatedly even though it executes only once

### ISSUE THREAD

**Issue by sharathkonda** [mucsi96/nightwatch-cucumber#60]
I got a scenario with steps but the cosole and the reports displays the same step couple of times.

Attached the html report and the cosole message:
<img width="751" alt="screen shot 2016-05-03 at 15 28 26" src="https://cloud.githubusercontent.com/assets/4320042/14986410/b5c3baf8-1143-11e6-9c1f-2bd533a1f286.png">
<img width="580" alt="screen shot 2016-05-03 at 15 26 22" src="https://cloud.githubusercontent.com/assets/4320042/14986413/b7d6abb6-1143-11e6-87c5-6221ead3e395.png">

**Comment by mucsi96** [comment]
Wow :) That's strange. Thanks for reporting

**Comment by G100g** [comment]
Me too! :)

**Comment by mucsi96** [comment]
Guys, please help me to reproduce the issue. A simple shareable test project is appreciated.

**Comment by mucsi96** [comment]
A fix is released in version `2.2.1`. Thanks for feedback!
