### ISSUE TITLE
Sometimes Cucumber console summary is not valid using Nightwatch runner

### ISSUE THREAD

**Issue by mucsi96** [mucsi96/nightwatch-cucumber#64]
This is because for the last test case the scenario result is fired before step result

**Comment by vamsys** [comment]
Hi
I started implementing the nightwatch-cucumber in my project and can see the issue, cucumber console reports last test as passed even though its failed!
Any guess when would this be fixed?
Can look into contributing for this if required.
regards

**Comment by mucsi96** [comment]
Hi @vamsys!
Your contribution would be very helpful! Currently I am rather busy.
Thank you

**Comment by LaurieSReynolds** [comment]
Is this an example of that?![screen shot 2016-07-29 at 3 38 10 pm](https://cloud.githubusercontent.com/assets/18370991/17267791/e24ddbbc-55c7-11e6-9f1c-4b052f0b502d.png)

**Comment by mucsi96** [comment]
Yes @LaurieSReynolds. I looks like this is an example of the issue.

**Comment by mucsi96** [comment]
Fixed in `4.1.1`
