### ISSUE TITLE
problem with html report

### ISSUE THREAD

**Issue by Alfredo81** [mucsi96/nightwatch-cucumber#65]
hi,
after the end of all tests  in reports folder i found only .xml file (for example FIREFOX_46.0.1_WINDOWS_google.xml)  and not the index.html with piechart and other report.
Can you help me please?

**Comment by mucsi96** [comment]
Thanks for feedback!
I will check it on a windows system.

**Comment by Alfredo81** [comment]
thank you so much,i'll wait for your answer!

**Comment by mucsi96** [comment]
This issue depends on a newly created Cucumber.JS issue https://github.com/cucumber/cucumber-js/issues/577
Feel free to vote for it or send a PR for quicker feedback :)
Currently I have no idea for a quick workaround.
Thanks for improving this tool!

**Comment by Alfredo81** [comment]
thank you to you for the great job on it!nightwatch-cucumber is awesome...do you think there is a similar  problem under Macosx?

**Comment by mucsi96** [comment]
Thanks you :) It's a Windows only problem :(

**Comment by Alfredo81** [comment]
Great under macosx works all fine!one suggestion...is possible to make log with timestamp? (for example 201605171740 --> year/month/day/hh:mm or something similar and unique for different tests)

**Comment by mucsi96** [comment]
A fix is released in version 2.2.2

**Comment by mucsi96** [comment]
Thanks for reporting the issue. I will check out the timestamp idea. Currently I am rather busy with university :)
