### ISSUE TITLE
Feature tag is not working

### ISSUE THREAD

**Issue by jeffrey-effendy** [mucsi96/nightwatch-cucumber#67]
I am running the following command to run the tests, in which I want to skip some of the tests, "node_modules/.bin/nightwatch --skiptags <tagname>", but it is not working. It is still running the features under the aforementioned <tagname>

**Comment by mucsi96** [comment]
Thanks for feedback! Can you try it again with version `2.2.3`. I created a testcase for skiptags case and it works ok. `node_modules/.bin/nightwatch --skiptags google-search`

**Comment by jeffrey-effendy** [comment]
Hi @mucsi96 after upgrading from 2.2.2 to 2.2.3, --skiptags and --tag work now!

**Comment by mucsi96** [comment]
Cool! Thanks for improving this package:)
