### ISSUE TITLE
Running a single feature with nightwatch

### ISSUE THREAD

**Issue by matthewroach** [mucsi96/nightwatch-cucumber#71]
Is it possible to running a single feature file using the nightwatch runner?

**Comment by mucsi96** [comment]
With current version it is not possible to filter for a single feature file. In the future I would like to add support for running 
```
$ nightwatch tests/one/firstTest.feature
``` 
or
```
$ nightwatch tests/one/firstTest.feature tests/secondTest.feature
```
Currently what you can do is
- Use some tags in the file. And run using `$ nightwatch --tag login`
- Use groups. To group tests together just place them in the same sub-folder. The folder name is the name of the group. And run using `$ nightwatch --group smoketests`

**Comment by matthewroach** [comment]
Thanks for quick reply @mucsi96. Tags and groups have helped a lot so far.

**Comment by aberonni** [comment]
I am able to achieve this using the `--filter` option. 

Lets say that for example you have `features\my_feature_file.feature` and in your nightwatch.conf.js: `featureFiles: 'features'`. 

You can then run:
`nightwatch --filter my_feature_file.*`

Hope that helps!

**Comment by mucsi96** [comment]
Thanks @aberonni!

**Comment by subhojit777** [comment]
@mucsi96 @aberonni Where do I mention this `featureFiles` setting. The setting is not documented.

**Comment by aberonni** [comment]
@subhojit777 I think it might be an old setting that has been deprecated - I can't really remember tbh! :(

I can see on the nightwatchjs page that the --filter option is still valid though

Maybe @mucsi96 can help

**Comment by subhojit777** [comment]
@aberonni Thanks for quick reply. Unfortunately `filter` or `exclude` is not working. I am using then per environment to achieve parallel running mode. Got the idea from [docs](https://github.com/nightwatchjs/nightwatch-docs/blob/master/guide/running-tests/run-parallel.md).

**Comment by aberonni** [comment]
@subhojit777 I think the only thing I can do at this point is link the [nightwatch doc](http://nightwatchjs.org/guide#command-line-options) that mentions this `filter` option - hope it helps

**Comment by dvidsilva** [comment]
@mucsi96 Q, is it possible to pass an environment using `--env` and run a single file. I can't seem to get it working.
