### ISSUE TITLE
Supports async step definitions?

### ISSUE THREAD

**Issue by RickEyre** [mucsi96/nightwatch-cucumber#75]
Promises would be nice for this as well.

**Comment by RickEyre** [comment]
Looks like it does ^-^

**Comment by airtonix** [comment]
Needs to be reopened because providing a callback breaks step definitions. see #129

**Comment by mucsi96** [comment]
Please take a look at my answer https://github.com/mucsi96/nightwatch-cucumber/issues/129#issuecomment-255808408
