### ISSUE TITLE
And statements aren't output to console.

### ISSUE THREAD

**Issue by RickEyre** [mucsi96/nightwatch-cucumber#76]
I have:

```cucumber
Given something
And another thing
Then something else
```

**Comment by mucsi96** [comment]
Hello @RickEyre ! Thanks for feedback!
Please use the recently created issue template https://github.com/mucsi96/nightwatch-cucumber/blob/master/.github/ISSUE_TEMPLATE.md
Thanks!

**Comment by mucsi96** [comment]
Please create a new issue. The issue template will be provided for you by GitHub. I am closing this issue.
