### ISSUE TITLE
steps.length is not a function

### ISSUE THREAD

**Issue by ldabiralai** [mucsi96/nightwatch-cucumber#79]
**Current behavior**
Running a test using nightwatch runner fails with ```steps.length is not a function```

![image](https://cloud.githubusercontent.com/assets/1711610/16344420/65f2e278-3a34-11e6-939c-9b813f60b584.png)

**Reproduction of the problem**
I'm running one test and upon forcing it to fail it errors as described.

**Please tell us about your environment:**

* **nightwatch-cucumber version: 3.0.0**

* **nightwatch version: 0.9.1**

* **cucumber version: 1.0.0**

* **Node.js version: 6.2.0**

**Comment by mucsi96** [comment]
@ldabiralai Thank you for contribution. Your fix is released in version `4.0.0`
