### ISSUE TITLE
this.api not available within page object

### ISSUE THREAD

**Issue by dhoward** [mucsi96/nightwatch-cucumber#86]
Hi. First of all thanks for the awesome library!

From the nightwatch docs it says that you should be able to access `this.api` inside a page object like so (following code taken directly from docs):
```
module.exports = {
  url: function() { 
    return this.api.launchUrl + '/login'; 
  },
  elements: {}
};
```

However, when I try to do the exact same thing `this.api` is undefined. I'm not sure whether it is user error, or a bug somewhere, or maybe the api is slightly different for `nightwatch-cucumber` than for regular nightwatch. Do you know if there is a way to access the api from inside a page object? Thanks!

**nightwatch-cucumber version: 4.0**
**nightwatch version: 0.9.1**
**cucumber version: 1.2**
**Node.js version: 6.2.2**

**Comment by mucsi96** [comment]
Hi @dhoward, 

Thank you for the feedback. I am not sure when can I fix this. Do you have time to check this? A contribution with pull request would be very appreciated :+1:

**Comment by mucsi96** [comment]
I checked this. But it was working fine.

**nightwatch-cucumber version: 4.1.1
nightwatch version: 0.9.6
cucumber version: 1.2.2
Node.js version: 5.11.0**

Can you update the versions and try it again?

**Comment by dhoward** [comment]
Looks like that fixed things, not sure exactly which package needed the update but the issue is gone. Thanks!

**Comment by dmerc** [comment]
i have the same issue, with newer versions:
nightwatch: "^0.9.12",
nightwatch-cucumber: "^7.0.10",
cucumber: "^2.0.0-rc.8",
Node.js: v6.10.0
