### ISSUE TITLE
Test gets a Type Error but the Test is marked as passed

### ISSUE THREAD

**Issue by XxJChavezxX** [mucsi96/nightwatch-cucumber#88]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
When you get a type error when running a test, the test is marked as passed with no failures

**Expected/desired behavior**
When running a test and a type error occurs, the test should be marked as failed

**Reproduction of the problem**
This can be reproduce by trying to a non-existent method when running a test

**Please tell us about your environment:**

* **nightwatch-cucumber version:**
4.1.1
* **nightwatch version:**
0.8.6
* **cucumber version:**
1.2.0
* **Node.js version:**
4.4.5

**Comment by mucsi96** [comment]
Thanks for your feedback!
Here a sample screenshot demonstrating the issue
![image](https://cloud.githubusercontent.com/assets/3163392/17906798/1dfbd500-6979-11e6-852d-b6a43d553013.png)

**Comment by XxJChavezxX** [comment]
Thanks for adding the screenshot :)

**Comment by mucsi96** [comment]
A fix is released in `4.1.2`. Please recheck

**Comment by XxJChavezxX** [comment]
Hmm the test suddenly finishes and leaves the browser instance open and no error is displayed
![screen shot 2016-08-25 at 2 21 55 pm](https://cloud.githubusercontent.com/assets/4723379/17986402/54982c1a-6acf-11e6-8d7f-5c0296548fb2.png)

**Comment by mucsi96** [comment]
Can you try it without paralell mode

**Comment by mucsi96** [comment]
Currently the paralell mode is not suppoted 100%. There is an improvement issue for that
