### ISSUE TITLE
Scenrio Outline Example Data from Json file

### ISSUE THREAD

**Issue by airtonix** [mucsi96/nightwatch-cucumber#92]
**I'm submitting a ...**  (check one with "x")

[  ] bug report
[ x ] feature request
[  ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber

**Current behavior**
Scenario outline example data has to be embeded as a markdown table.

**Expected/desired behavior**

```
Examples:
    file: './example.(json|yml|csv|md)'
```

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://c9.io, http://www.koding.com, https://www.nitrous.io or similar.

**What is the expected behavior?**

same as current

**What is the motivation / use case for changing the behavior?**

- less typing
- reuse of data

**Please tell us about your environment:**

- fedora 22 64bit

* **nightwatch-cucumber version:**
* **nightwatch version:**
* **cucumber version:**

```json
...
    "cucumber": "^1.2.2",
...
    "nightwatch-cucumber": "^4.1.2",
    "nightwatch": "^0.9.6",
...
```

* **Node.js version:**

```bash
$  npm --version
3.10.5

$ node --version
v4.4.7
```

**Comment by aberonni** [comment]
+1 this would be really cool

**Comment by mucsi96** [comment]
Thanks @airtonix for the feedback!

Is this feature supported by Cucumber.js?
If not please raise a ticket there

**Comment by mucsi96** [comment]
I am closing this issue. As there is no plan to fix it here
