### ISSUE TITLE
step from step definitions

### ISSUE THREAD

**Issue by Alfredo81** [mucsi96/nightwatch-cucumber#95]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

add a step from step definitions  adding this lib https://github.com/hackhat/cucumberry and modifying for nightwatch/cucumber  would be great(At the moment cucumber don't have step from step in javascript but only in ruby)

**Comment by mucsi96** [comment]
Thank you @Alfredo81 for your feedback. I think this is not in the scope of this plugin. Please raise an issue for Cucumber.js. Also I don't really agree with calling steps with textual parameter a good thing. For code reuse you can use functions, page objects, etc. Also text can be easily misspelled and could not detected by a code style analyzer. Step definitions are not for business. They are for programmers. I am closing this issue as there is no plan for fixing this.
